"""Golden structure spec for 25356487E_CONTRATO.pdf page 1.

ASNEF model F_AS-5 vehicle-loan cover page (CaixaBank Payments & Consumer):
intervinientes (comprador-prestatario, fiador, financiador, vendedor), objeto a
financiar, and economic conditions of the loan. Generated by golden-scaffolder.
"""

PDF = "/Users/carlos/Edelwyss/Projects/docomestria/Dataset/25356487E_CONTRATO.pdf"
PAGE = 1

META = {
    "document_type": "Contrato de préstamo de financiación a comprador de bienes muebles",
    "annotator": "scaffolder",
    "covers_cases": [
        "asnef_vehicle_loan_cover",
        "person_inline_name_columns",
        "fiador_block",
        "financiador_block",
        "objeto_a_financiar",
        "economic_conditions_inline",
    ],
}


STRUCTURE = [
    {"type": "noise", "id": "banner_modelo", "text": "Nº Modelo F_AS-5",
     "kind": "watermark", "y_hint": 22.7},
    {"type": "noise", "id": "hoja_num", "text": "Hoja nº ......1/25......",
     "kind": "page_number", "y_hint": 35.4},
    {"type": "noise", "id": "banner_contrato",
     "text": "CONTRATO DE PRÉSTAMO DE FINANCIACIÓN A COMPRADOR DE BIENES MUEBLES",
     "kind": "watermark", "y_hint": 86.3},
    {"type": "noise", "id": "sidebar_logalty",
     "text": "Logalty Guid: 001001-0001-000000076308655.par - Date: 2022/07/11 T 19:08:36 CEST +0200 - Pages: 1/40",
     "kind": "logalty_metadata", "y_hint": 271.9},

    {"type": "section", "id": "encabezado", "title": "Encabezado", "y_hint": 60.8,
     "children": [
        {"type": "kv_leaf", "id": "nro_contrato", "label": "Nº",
         "value": "202207590875462", "y_hint": 60.4},
        {"type": "prose_block", "id": "modelo_aprobado", "label": "Modelo aprobado",
         "text": "Modelo aprobado a la ASNEF por la Dirección General de los Registros y del "
                 "Notariado (DGRN) 04/02/2000. Modificado por Resoluciones de DGRN de "
                 "23/05/2006, de 29/09/2011, de 02/07/2013, de 23/01/2014, de 07/10/2019 y "
                 "de 07/06/2021",
         "y_hint": 99.0},
        {"type": "kv_leaf", "id": "impreso_nro", "label": "IMPRESO Nº",
         "value": "4684001", "y_hint": 144.6},
     ]},

    {"type": "section", "id": "comprador_prestatario",
     "title": "DATOS PERSONALES O DENOMINACIÓN SOCIAL, EN SU CASO, DEL COMPRADOR-PRESTATARIO (1)",
     "y_hint": 166.0,
     "children": [
        {"type": "kv_group", "id": "comprador_datos", "pairs": [
            {"label": "1er Apellido", "value": "VEGA", "y_hint": 189.2, "x_hint": 103.7},
            {"label": "2º Apellido", "value": "LLIVE", "y_hint": 189.2, "x_hint": 217.9},
            {"label": "Nombre", "value": "EDWIN GEOVANNY", "y_hint": 189.2, "x_hint": 289.3},
            {"label": "NIF/CIF", "value": "25356487E", "y_hint": 189.2, "x_hint": 444.6},
            {"label": "Domicilio", "value": "DOCE DE OCTUBRE,36 PISO 2 - I - ZARAGOZA", "y_hint": 206.8},
            {"label": "Tel", "value": "610696765", "y_hint": 205.6, "x_hint": 398.2},
            {"label": "Correo electrónico", "value": "GEOVANNY_0_0_7@HOTMAIL.COM", "y_hint": 222.0},
            {"label": "Inscrita en", "value": "", "y_hint": 222.4},
            {"label": "Y en su nombre", "value": "", "y_hint": 239.0},
        ]},
     ]},

    {"type": "section", "id": "fiador",
     "title": "DATOS PERSONALES O DENOMINACIÓN SOCIAL, EN SU CASO, DEL FIADOR (2)",
     "y_hint": 261.7,
     "children": [
        {"type": "kv_group", "id": "fiador_datos", "pairs": [
            {"label": "1er Apellido", "value": "TAMAYO", "y_hint": 282.4, "x_hint": 96.5},
            {"label": "2º Apellido", "value": "JIJON", "y_hint": 282.4, "x_hint": 217.9},
            {"label": "Nombre", "value": "ALEJANDRA ESTEFANIA", "y_hint": 282.4, "x_hint": 278.0},
            {"label": "NIF/CIF", "value": "26275362R", "y_hint": 282.4, "x_hint": 444.6},
            {"label": "Domicilio", "value": "PRADILLA,13 PISO 3 - C - ZARAGOZA", "y_hint": 302.5},
            {"label": "Tel", "value": "611630330", "y_hint": 301.3, "x_hint": 398.2},
            {"label": "Correo electrónico", "value": "GLORIAJ_24@HOTMAIL.COM", "y_hint": 318.0},
            {"label": "Inscrita en", "value": "", "y_hint": 318.3},
            {"label": "Y en su nombre", "value": "", "y_hint": 334.7},
        ]},
     ]},

    {"type": "section", "id": "financiador", "title": "FINANCIADOR", "y_hint": 366.7,
     "children": [
        {"type": "kv_group", "id": "financiador_datos", "pairs": [
            {"label": "Financiador",
             "value": "CAIXABANK PAYMENTS & CONSUMER, E.F.C., E.P., S.A.U.", "y_hint": 366.7},
            {"label": "D. (representante)", "value": "LUIS LAGARES PUIG", "y_hint": 366.7, "x_hint": 326.0},
            {"label": "NIF", "value": "35063208F", "y_hint": 383.4},
            {"label": "con poder otorgado ante notario de", "value": "BARCELONA",
             "y_hint": 384.5, "x_hint": 116.9},
            {"label": "D.", "value": "TOMAS GIMENEZ DUART", "y_hint": 384.5, "x_hint": 368.1},
            {"label": "con fecha", "value": "12-02-2013", "y_hint": 400.9},
        ]},
     ]},

    {"type": "section", "id": "vendedor",
     "title": "VENDEDOR/ INTERMEDIARIO FINANCIERO", "y_hint": 417.6,
     "children": [
        {"type": "kv_group", "id": "vendedor_datos", "pairs": [
            {"label": "Vendedor/Intermediario financiero", "value": "FLEXICAR CAPITAL SL.",
             "y_hint": 417.6},
            {"label": "Domicilio social", "value": "ALMENDRO ,Nº 4 , 28942 FUENLABRADA",
             "y_hint": 434.2},
        ]},
     ]},

    {"type": "section", "id": "objeto_a_financiar", "title": "OBJETO A FINANCIAR (3)",
     "y_hint": 450.9,
     "children": [
        {"type": "kv_group", "id": "objeto_datos", "pairs": [
            {"label": "Objeto a financiar", "value": "TODO TERRENO", "y_hint": 450.9, "x_hint": 27.0},
            {"label": "Marca", "value": "BMW", "y_hint": 450.9, "x_hint": 280.7},
            {"label": "Modelo", "value": "X1 F48 DIESEL", "y_hint": 450.9, "x_hint": 395.4},
            {"label": "Nº fabricación o chasis", "value": "WBAJH110705N04529", "y_hint": 467.3, "x_hint": 27.0},
            {"label": "Matrícula (en su caso)", "value": "5888KVV", "y_hint": 467.3, "x_hint": 267.1},
        ]},
     ]},

    {"type": "section", "id": "condiciones_economicas", "title": "Condiciones económicas",
     "y_hint": 493.7,
     "children": [
        {"type": "kv_group", "id": "importes_base", "pairs": [
            {"label": "Precio de compraventa (valor contado)", "value": "25.780,00€", "y_hint": 494.8},
            {"label": "Desembolso inicial, (en su caso)", "value": "5.000,00€", "y_hint": 514.4},
            {"label": "Capital inicial del préstamo.", "value": "20.780,00€€", "y_hint": 532.4},
        ]},

        {"type": "table", "id": "comisiones", "title": "Espacio reservado para incluir las comisiones, gastos etc.",
         "y_hint": 554.3,
         "columns": [
             {"id": "tipo", "label": "Tipo", "type": "text"},
             {"id": "comision_apertura", "label": "Comisión apertura", "type": "amount"},
             {"id": "comision_estudio", "label": "Comisión Estudio", "type": "amount"},
         ],
         "rows": [
             {"tipo": ("Financiadas", 571.2), "comision_apertura": ("820,81", 570.8, 230.6),
              "comision_estudio": ("0,00", 570.8, 441.6)},
             {"tipo": ("No Financiadas", 587.8), "comision_apertura": ("", 587.8),
              "comision_estudio": ("", 587.8)},
         ]},

        {"type": "table", "id": "servicios_accesorios",
         "title": "Espacio reservado para Servicios accesorios relacionados (mantenimiento, seguros, etc.)",
         "y_hint": 625.5,
         "columns": [
             {"id": "tipo", "label": "Tipo", "type": "text"},
             {"id": "coste_seguro_mensual", "label": "Coste del seguro mensual", "type": "amount"},
         ],
         "rows": [
             {"tipo": ("Condicionantes", 642.1), "coste_seguro_mensual": ("", 642.1)},
             {"tipo": ("No Condicionantes", 658.8), "coste_seguro_mensual": ("24,94", 658.4)},
         ]},

        {"type": "kv_leaf", "id": "importe_total_prestamo",
         "label": "Importe Total del Préstamo (Capital+Otros conceptos financiados)",
         "value": "21.600,81€", "y_hint": 677.6},
     ]},

    {"type": "prose_block", "id": "datos_financiador", "label": "Datos del financiador",
     "text": "Datos del financiador: CaixaBank Payments & Consumer, E.F.C., E.P., S.A.U., "
             "domiciliada en Calle Caleruega, 102, de (28033) Madrid, CIF A-08980153- "
             "Inscrita en el Registro Mercantil de Madrid, Tomo 36.556, Folio 29, Hoja "
             "M-656.492 e inscrita con el nº 8776 en el Registro de Establecimientos de "
             "Crédito del Banco de España.",
     "y_hint": 759.3},

    {"type": "noise", "id": "footer_mod", "text": "MOD. (M) 006-720.0313-02 (21) - 24 de mayo de 2022",
     "kind": "watermark", "y_hint": 783.9},
    {"type": "noise", "id": "footer_reverso",
     "text": "REVERSO SÓLO APTO PARA LA IMPRESIÓN DE LAS CONDICIONES PARTICULARES CONTENIDAS EN EL B. O.",
     "kind": "watermark", "y_hint": 799.5},
]
