"""Golden structure spec for 25356487E_CONTRATO.pdf page 26 (CaixaBank SEPA direct debit mandate).

Orden de domiciliación de adeudo directo SEPA: header KVs, intro prose, Datos del
deudor / Datos del acreedor tables, subyacente info, deudor signature box.
Generated by golden-scaffolder. Walker-compatible types only.
"""

PDF = "/Users/carlos/Edelwyss/Projects/docomestria/Dataset/25356487E_CONTRATO.pdf"
PAGE = 26

META = {
    "document_type": "orden_domiciliacion_sepa",
    "annotator": "scaffolder",
    "covers_cases": [
        "sepa_mandate_header",
        "two_col_kv_table",
        "intro_prose_block",
        "signature_placeholder",
        "page_noise_logalty",
    ],
}


STRUCTURE = [
    {"type": "noise", "id": "banner", "kind": "watermark", "y_hint": 48,
     "text": "SOLICITUD-CONTRATO DE FINANCIACIÓN ORDEN DE DOMICILIACIÓN DE ADEUDO DIRECTO SEPA"},

    {"type": "kv_group", "id": "cabecera",
     "pairs": [
         {"label": "Lugar", "value": "FUENLABRADA", "y_hint": 89, "x_hint": 25.6},
         {"label": "Fecha", "value": "11-07-2022", "y_hint": 88, "x_hint": 235.4},
         {"label": "Referencia", "value": "20220759087546201", "y_hint": 84, "x_hint": 339.4},
     ]},

    {"type": "prose_block", "id": "intro_mandato", "label": "Información del mandato",
     "y_hint": 108,
     "text": "El número de la orden de domiciliación coincide con el de la solicitud/contrato de "
             "financiación al que afectará. Mediante la firma de esta orden de domiciliación, el "
             "deudor autoriza a CaixaBank Payments & Consumer, E.F.C., E.P., S.A.U. (en adelante "
             "CaixaBank Payments & Consumer) a enviar instrucciones a dicha entidad del deudor para "
             "adeudar su cuenta y a la entidad para efectuar los adeudos en su cuenta siguiendo las "
             "instrucciones de CaixaBank Payments & Consumer. Como parte de sus derechos, el deudor "
             "está legitimado al reembolso por su entidad, en los términos y condiciones del contrato "
             "suscrito con la misma. La solicitud de reembolso deberá efectuarse dentro de las ocho "
             "semanas que siguen a la fecha de adeudo en cuenta."},

    {"type": "section", "id": "datos_deudor", "title": "Datos del deudor", "y_hint": 187,
     "children": [
         {"type": "table", "id": "datos_deudor_tabla", "y_hint": 217,
          "columns": [
              {"id": "label", "label": "Campo", "type": "text"},
              {"id": "value", "label": "Valor", "type": "text"},
          ],
          "rows": [
              {"label": ("Su nombre", 217), "value": ("EDWIN GEOVANNY VEGA LLIVE", 219)},
              {"label": ("Su dirección", 237), "value": ("DOCE DE OCTUBRE,36 PISO 2 - I", 238)},
              {"label": ("Código postal y Ciudad", 255), "value": ("50017 ZARAGOZA", 257)},
              {"label": ("País", 275), "value": ("ESPAÑA", 276)},
              {"label": ("Su número de cuenta*", 294), "value": ("ES12 0182 6908 9502 0154 3190", 296)},
          ]},
     ]},

    {"type": "prose_block", "id": "nota_cuenta", "label": "Nota cuenta", "y_hint": 313,
     "text": "* Esta cuenta complementa y, si es el caso, sustituye a la indicada en las Condiciones "
             "Particulares de la Solicitud/Contrato de financiación."},

    {"type": "section", "id": "datos_acreedor", "title": "Datos del acreedor", "y_hint": 336,
     "children": [
         {"type": "table", "id": "datos_acreedor_tabla", "y_hint": 366,
          "columns": [
              {"id": "label", "label": "Campo", "type": "text"},
              {"id": "value", "label": "Valor", "type": "text"},
          ],
          "rows": [
              {"label": ("Nombre del acreedor", 366), "value": ("CaixaBank Payments & Consumer, E.F.C., E.P., S.A.U.", 365)},
              {"label": ("Identificador del acreedor", 385), "value": ("A-08980153", 385)},
              {"label": ("Nombre de la calle y número", 405), "value": ("C/ Caleruega 102", 405)},
              {"label": ("Código postal y Ciudad", 424), "value": ("28033 Madrid", 424)},
              {"label": ("País", 443), "value": ("España", 443)},
              {"label": ("Tipo de pago", 462), "value": ("Pago recurrente", 462)},
          ]},
     ]},

    {"type": "section", "id": "relacion_subyacente",
     "title": "Información sobre la relación subyacente entre el acreedor y el deudor – a título meramente informativo",
     "y_hint": 489,
     "children": [
         {"type": "kv_leaf", "id": "cod_id_deudor", "label": "Código de identificación del deudor",
          "value": "25356487E", "y_hint": 521},
     ]},

    {"type": "kv_group", "id": "firma_cabecera",
     "pairs": [
         {"label": "Localidad de firma", "value": "FUENLABRADA", "y_hint": 546, "x_hint": 29.5},
         {"label": "Fecha", "value": "11-07-2022", "y_hint": 546, "x_hint": 243.8},
     ]},

    {"type": "signature_placeholder", "id": "firma_deudor",
     "label": "Firma del deudor", "value": "", "y_hint": 575},

    {"type": "prose_block", "id": "nota_derechos", "label": "Nota derechos", "y_hint": 661,
     "text": "Nota: Puede obtener información adicional sobre sus derechos en su entidad financiera."},

    {"type": "noise", "id": "pagina", "kind": "page_number", "y_hint": 269, "text": "26/40"},
    {"type": "noise", "id": "logalty_meta", "kind": "logalty_metadata", "y_hint": 691,
     "text": "Logalty Guid: 001001-0001-000000076308655.par - Date: 2022/07/11 T 19:08:36 CEST +0200"},
    {"type": "noise", "id": "footer_izq", "kind": "watermark", "y_hint": 784,
     "text": "Documento de uso exclusivo del acreedor."},
    {"type": "noise", "id": "footer_mod", "kind": "watermark", "y_hint": 784,
     "text": "MOD. (M) 006-720.0085-84 (04) - 17 de julio de 2019"},
]
