"""Golden structure spec for 25356487E_CONTRATO.pdf page 27.

CaixaBank INE (European standardised consumer-credit information) for a
PRESTAMO MERCANTIL: header banner + 3 numbered sections (lender identity,
product characteristics, costs) in a 2-col label/value layout.

Generated by golden-scaffolder. Walker-compatible types only.
"""

PDF = "/Users/carlos/Edelwyss/Projects/docomestria/Dataset/25356487E_CONTRATO.pdf"
PAGE = 27

META = {
    "document_type": "INE_credito_consumo",
    "annotator": "scaffolder",
    "covers_cases": [
        "ine_header_banner",
        "lender_identity_kv",
        "two_col_label_value_table",
        "inline_amount_in_prose",
        "checkbox_consent",
        "logalty_sidebar_noise",
    ],
}


STRUCTURE = [
    # --- Top banner: watermark/title, classified as noise ---
    {"type": "noise", "id": "banner_ine", "kind": "watermark",
     "text": "INFORMACIÓN NORMALIZADA EUROPEA (INE) SOBRE EL CRÉDITO AL CONSUMO PRÉSTAMO MERCANTIL",
     "y_hint": 63.6},

    # --- Place / date / solicitud line ---
    {"type": "kv_leaf", "id": "lugar", "label": "En",
     "value": "FUENLABRADA", "y_hint": 90.4, "x_hint": 27.0},
    {"type": "kv_leaf", "id": "fecha_dia", "label": "a",
     "value": "11", "y_hint": 90.4, "x_hint": 186.9},
    {"type": "kv_leaf", "id": "fecha_mes", "label": "de",
     "value": "Julio", "y_hint": 90.4, "x_hint": 215.3},
    {"type": "kv_leaf", "id": "fecha_anio", "label": "de",
     "value": "2022", "y_hint": 90.4, "x_hint": 268.9},
    {"type": "kv_leaf", "id": "nro_solicitud", "label": "Nº SOLICITUD",
     "value": "202207590875462", "y_hint": 90.4, "x_hint": 318.9, "label_x_hint": 318.9},

    # --- Intro prose ---
    {"type": "prose_block", "id": "preambulo", "label": "Preámbulo",
     "text": "Este documento sirve para informarle sobre las condiciones del producto de financiación que le ofrece CaixaBank Payments & Consumer, en base a las preferencias que ha manifestado para que así pueda compararlas con las ofertas de otras entidades. Dispone del tiempo que considere necesario para analizar esta información antes de decidir si firma el contrato. Las informaciones resaltadas con sombreado en este INE son especialmente relevantes.",
     "y_hint": 106.3},

    # --- Section 1: lender / intermediary identity ---
    {"type": "section", "id": "identidad_prestamista",
     "title": "1. Identidad y detalles de contacto del prestamista y/o del intermediario",
     "y_hint": 145.2,
     "children": [
         {"type": "kv_leaf", "id": "prestamista", "label": "Prestamista",
          "value": "CaixaBank Payments & Consumer, E.F.C., E.P., S.A.U., (en adelante, CaixaBank Payments & Consumer)",
          "y_hint": 157.9, "x_hint": 163.3},
         {"type": "kv_leaf", "id": "direccion_prestamista", "label": "Dirección",
          "value": "C/ Caleruega, 102 28033 Madrid", "y_hint": 168.8, "x_hint": 163.3},
         {"type": "kv_leaf", "id": "web", "label": "Dirección de página web",
          "value": "http://www.caixabankpc.com", "y_hint": 179.2, "x_hint": 163.3},
         {"type": "kv_leaf", "id": "intermediario", "label": "Intermediario del crédito",
          "value": "FLEXICAR CAPITAL SL.", "y_hint": 192.5, "x_hint": 163.3},
         {"type": "kv_leaf", "id": "direccion_intermediario", "label": "Dirección",
          "value": "ALMENDRO ,Nº 4 , 28942 FUENLABRADA", "y_hint": 202.4, "x_hint": 163.3},
     ]},

    # --- Section 2: product characteristics ---
    {"type": "section", "id": "caracteristicas_producto",
     "title": "2. Descripción de las características principales del producto de crédito",
     "y_hint": 210.6,
     "children": [
         {"type": "kv_leaf", "id": "tipo_credito", "label": "Tipo de crédito",
          "value": "Préstamo. La financiación propuesta regula las relaciones entre usted (Titular), de una parte, y CaixaBank Payments & Consumer, de otra, respecto de la concesión a aquél (titular) de un préstamo (en adelante, denominado “Préstamo Mercantil” o “Préstamo”), por el importe indicado en este INE, para financiar la compra de bienes y/o contratación de servicios.",
          "y_hint": 222.4, "x_hint": 163.3},
         {"type": "kv_leaf", "id": "importe_total_credito", "label": "Importe total del crédito.",
          "value": "21.600,81", "y_hint": 316.4, "x_hint": 275.7, "label_x_hint": 27.0},
         {"type": "kv_leaf", "id": "condiciones_disposicion",
          "label": "Condiciones que rigen la disposición del crédito.",
          "value": "CaixaBank Payments & Consumer abonará directamente al Establecimiento, por cuenta del titular, el importe de las compras o servicios adquiridos mediante el Préstamo, tras el estudio previo, la aprobación de la solicitud del mismo, y la recepción de la documentación requerida.",
          "y_hint": 350.4, "x_hint": 163.3},
         {"type": "kv_leaf", "id": "duracion_meses", "label": "Duración del contrato de crédito",
          "value": "108", "y_hint": 378.8, "x_hint": 290.2, "label_x_hint": 27.0},
         {"type": "kv_group", "id": "modalidad_pago",
          "pairs": [
              {"label": "Cuota primera", "value": "328,93", "y_hint": 398.7, "x_hint": 213.5},
              {"label": "Cuota última", "value": "328,93", "y_hint": 399.4, "x_hint": 296.5},
              {"label": "Cuotas restantes", "value": "328,93", "y_hint": 398.4, "x_hint": 394.0},
          ]},
         {"type": "kv_group", "id": "intereses_gastos",
          "pairs": [
              {"label": "Importe Intereses", "value": "11.230,11 euros.", "y_hint": 435.9, "x_hint": 252.1},
              {"label": "Importe Comisión de apertura", "value": "820,81 euros, que se pagará:", "y_hint": 443.7, "x_hint": 282.6},
              {"label": "Importe Comisión de estudio", "value": "0,00", "y_hint": 459.0, "x_hint": 289.5},
          ]},
         {"type": "kv_leaf", "id": "importe_total_pagar", "label": "Importe total que deberá usted pagar.",
          "value": "35.524,44 euros.", "y_hint": 480.0, "x_hint": 225.3, "label_x_hint": 27.0},
         {"type": "kv_leaf", "id": "objeto_financiado", "label": "Objeto Financiado: Vehículo.",
          "value": "TODO TERRENO", "y_hint": 514.5, "x_hint": 244.0, "label_x_hint": 163.3},
         {"type": "kv_leaf", "id": "precio_contado",
          "label": "Importe del bien/servicio al contado (Precio de compraventa -Valor contado-)",
          "value": "25.780,00", "y_hint": 539.4, "x_hint": 390.8, "label_x_hint": 163.3},
         {"type": "kv_leaf", "id": "garantias", "label": "Garantías requeridas.",
          "value": "No aplica Reserva de dominio Cuando aplique.", "y_hint": 561.5, "x_hint": 163.3, "label_x_hint": 27.0},
         {"type": "kv_leaf", "id": "prelacion_pagos",
          "label": "Los reembolsos no suponen la inmediata amortización del capital",
          "value": "Todos los pagos recibidos serán aplicados con la siguiente prelación: (i) costas y gastos suplidos por CaixaBank Payments & Consumer; (ii) comisiones devengadas; (iii) penalidades (penas e intereses de demora incluidos); (iv) intereses ordinarios; (v) capital del Préstamo.",
          "y_hint": 593.4, "x_hint": 163.3},
     ]},

    # --- Section 3: costs ---
    {"type": "section", "id": "costes_credito",
     "title": "3. Costes del crédito",
     "y_hint": 612.1,
     "children": [
         {"type": "kv_leaf", "id": "tin", "label": "Tipo de interés Nominal del Préstamo Mercantil",
          "value": "9,99", "y_hint": 623.3, "x_hint": 336.4, "label_x_hint": 163.3},
         {"type": "kv_leaf", "id": "tae", "label": "TAE del Préstamo Mercantil",
          "value": "11,58", "y_hint": 653.6, "x_hint": 283.5, "label_x_hint": 163.3},
         {"type": "kv_group", "id": "seguro_obligatorio",
          "pairs": [
              {"label": "¿Es obligatoria la contratación del seguro?", "value": "X No", "y_hint": 699.4, "x_hint": 167.0},
              {"label": "¿Objeto financiado asociado a contratos de suministro?", "value": "X No", "y_hint": 742.8, "x_hint": 167.0},
          ]},
     ]},

    # --- Sidebar / footer noise ---
    {"type": "noise", "id": "barcode", "kind": "watermark",
     "text": "202207590875462", "y_hint": 48.5},
    {"type": "noise", "id": "footer_pages", "kind": "logalty_metadata",
     "text": "27/40", "y_hint": 269.5},
    {"type": "noise", "id": "sidebar_logalty", "kind": "logalty_metadata",
     "text": "Logalty Guid: 001001-0001-000000076308655.par", "y_hint": 691.9},
    {"type": "noise", "id": "footer_mod", "kind": "logalty_metadata",
     "text": "MOD. (M) 006.INAU.0.TE.720 (01) - 22 de marzo de 2022 Página 1/2", "y_hint": 790.0},
]
