"""Golden structure spec for 25356487E_CONTRATO.pdf page 28 (28/40).

SEPI / Información Normalizada Europea precontractual credit-info form,
page 2/2: a 2-column label/value table grouped into thematic sections
(Costes relacionados tail, "4. Otros aspectos jurídicos importantes",
"5. Información adicional en el caso de comercialización a distancia").
Generated by golden-scaffolder. Walker-compatible types only.
"""

import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from _patterns import condiciones_table


def _condiciones_table_x(table_id, title, y_hint, rows):
    """Like condiciones_table but each row may carry a value x_hint.

    Row tuple: (label, label_y, value, value_y[, value_x]).
    When value_x is present the value cell is emitted as a 3-tuple so the
    walker disambiguates the value column from the label column. Needed where
    pdfplumber merges label+value onto one reconstructed row (binary "Sí"
    cells) or where the label text is a substring of the full value text
    (e.g. "Registro" inside the Registro cell).
    """
    out_rows = []
    for r in rows:
        label = (r[0], r[1])
        value = (r[2], r[3], r[4]) if len(r) >= 5 and r[4] is not None else (r[2], r[3])
        out_rows.append({"label": label, "value": value})
    return {
        "type": "table",
        "id": table_id,
        "title": title,
        "y_hint": y_hint,
        "columns": [
            {"id": "label", "label": "Concepto", "type": "text"},
            {"id": "value", "label": "Valor", "type": "text"},
        ],
        "rows": out_rows,
    }


PDF = "/Users/carlos/Edelwyss/Projects/docomestria/Dataset/25356487E_CONTRATO.pdf"
PAGE = 28

META = {
    "document_type": "informacion_normalizada_europea_credito_consumo",
    "annotator": "scaffolder",
    "covers_cases": [
        "sepi_two_column_label_value_table",
        "multiline_value_fusion",
        "binary_si_no_value",
        "no_aplica_value",
        "thematic_subsections",
        "logalty_sidebar_noise",
        "value_x_hint_disambiguation",
    ],
}


STRUCTURE = [
    # -----------------------------------------------------------------
    # Tail of "Costes relacionados" block carried over from prior page.
    # f02: pagos atrasados value now captures the full multi-line cell
    # (Interés de demora + Compensación por costes de cobro, incl. the
    # 35€/60€/24€/300€ thresholds). value_x=163.3 forces the value column.
    # -----------------------------------------------------------------
    _condiciones_table_x(
        "costes_relacionados",
        "Costes relacionados",
        28,
        [
            ("Para mantener una o varias cuentas se requiere registrar tanto las "
             "transacciones de pago como la disposición del crédito.", 39,
             "No aplica", 41),
            ("Importe de los costes por utilizar un medio de pago específico (por "
             "ejemplo, una tarjeta de crédito).", 65,
             "No aplica", 64),
            ("Condiciones en que pueden modificarse los gastos antes mencionados "
             "relacionados con el contrato de crédito.", 89,
             "No aplica", 90),
            ("Costes en caso de pagos atrasados. La no realización de un pago podrá "
             "acarrearle graves consecuencias (por ejemplo, la inclusión en Sistemas "
             "de Información Crediticia, así como el embargo y la venta forzosa de sus "
             "bienes).", 114,
             "Interés de demora: TIN de cada disposición + dos puntos porcentuales. "
             "Compensación por costes de cobro ante un impago (retraso en el pago): "
             "35€ por los recursos que CaixaBank Payments & Consumer destinará a poner "
             "al día la deuda impagada. Un mismo impago no podrá generar más de una "
             "compensación. Sólo se cobrará esta compensación en deudas iguales o "
             "superiores a 60€. Si después de 15 días se mantiene el impago, CaixaBank "
             "Payments & Consumer podrá enviar al titular un burofax o equivalente con "
             "certificación de contenido y recibo. Actualmente tiene un coste de 24€ y "
             "CaixaBank Payments & Consumer reclamará al titular su coste en deudas "
             "superiores a 300€.", 113, 163.3),
        ],
    ),

    # -----------------------------------------------------------------
    # Section 4 — Otros aspectos jurídicos importantes
    # -----------------------------------------------------------------
    {
        "type": "section",
        "id": "otros_aspectos_juridicos",
        "title": "4. Otros aspectos jurídicos importantes",
        "y_hint": 165,
        "children": [
            _condiciones_table_x(
                "aspectos_juridicos",
                "Otros aspectos jurídicos importantes",
                176,
                [
                    # f01: pdfplumber merges this label row with the value "Sí"
                    # onto one reconstructed row, so without x_hint it links the
                    # "si" inside "desistimiento" (x=65.7, label column). value_x
                    # 164.7 forces the value-column "Sí" atom (matches liteparse).
                    ("Derecho de desistimiento. Usted tiene derecho a desistir del "
                     "contrato de crédito en el plazo de 14 días naturales.", 176,
                     "Sí", 178, 164.7),
                    ("Reembolso anticipado. Usted tiene derecho a reembolsar "
                     "anticipadamente el crédito total o parcialmente en cualquier "
                     "momento.", 201,
                     "Sí", 203, 164.7),
                    ("El prestamista tiene derecho a compensación en caso de reembolso "
                     "anticipado.", 234,
                     "Compensación por cancelación anticipada total o parcial : 1,00% "
                     "del importe del crédito reembolsado anticipadamente si el periodo "
                     "restante,", 235),
                    ("Consulta de una base de datos. El prestamista tiene que informarle "
                     "de inmediato y sin cargo del resultado de una consulta de una base "
                     "de datos si se rechaza la solicitud de crédito sobre la base de una "
                     "consulta de ese tipo. Esto no se aplica si la difusión de esa "
                     "información está prohibida por una ley o por el Derecho de la Unión "
                     "Europea o es contraria a los objetivos de orden público o de la "
                     "seguridad pública.", 254,
                     "CaixaBank Payments & Consumer informa al titular del derecho que le "
                     "asiste a consultar sus datos a fuentes reconocidas en derecho que "
                     "considere", 254),
                    ("Derecho a un proyecto del contrato de crédito. Usted tiene derecho, "
                     "previa petición, a obtener de forma gratuita una copia del proyecto "
                     "de contrato de crédito. Esta disposición no se aplicará si en el "
                     "momento de la solicitud el prestamista no está dispuesto a celebrar "
                     "con usted el contrato de crédito.", 325,
                     "CaixaBank Payments & Consumer, siempre que esté dispuesta a conceder "
                     "la financiación, facilitará al titular, solicitante del crédito, de "
                     "forma gratuita, previa", 326),
                    ("Período durante el cual el prestamista está vinculado por la "
                     "información precontractual.", 379,
                     "Esta información precontractual será válida desde la fecha que figura "
                     "en el encabezamiento de este documento y hasta 30 días naturales", 379),
                    ("Utilización de un instrumento de pago específico, como por ejemplo, "
                     "una tarjeta de crédito.", 398,
                     "No aplica", 398),
                ],
            ),
        ],
    },

    # -----------------------------------------------------------------
    # Section 5 — Información adicional (comercialización a distancia)
    # -----------------------------------------------------------------
    {
        "type": "section",
        "id": "info_adicional_distancia",
        "title": "5. Información adicional en el caso de comercialización a distancia de servicios financieros",
        "y_hint": 422,
        "children": [
            {
                "type": "section",
                "id": "relativa_prestamista",
                "title": "a) Relativa al prestamista",
                "y_hint": 435,
                "children": [
                    _condiciones_table_x(
                        "datos_prestamista",
                        "Relativa al prestamista",
                        446,
                        [
                            # f03: full Registro cell (both spans, incl. the Banco
                            # de España nº 8776 disclosure). value_x=161.9 forces
                            # the value column — without it the "Registro" substring
                            # collides with the label span (x=25.6).
                            ("Registro", 446,
                             "CaixaBank Payments & Consumer (NIF A-08980153) está inscrita "
                             "en el Registro Mercantil de Madrid, Tomo 36.556, Folio 29, "
                             "Hoja M-656.492 e inscrita con el nº 8776 en el Registro de "
                             "Establecimientos de Crédito del Banco de España.", 446, 161.9),
                            ("Autoridad de supervisión", 466,
                             "CaixaBank Payments & Consumer está sometida a la supervisión "
                             "del Banco de España, con domicilio en Madrid, calle Alcalá, 50.", 466),
                        ],
                    ),
                ],
            },
            {
                "type": "section",
                "id": "relativa_contrato",
                "title": "b) Relativa al contrato de crédito",
                "y_hint": 478,
                "children": [
                    condiciones_table(
                        "datos_contrato",
                        "Relativa al contrato de crédito",
                        487,
                        [
                            ("Ejercicio del derecho de desistimiento", 487,
                             "Conforme a lo establecido en la Ley 16/2011, de 24 de junio, "
                             "de Contratos de Crédito al Consumo, en el supuesto de que el/los "
                             "prestatario/s", 487),
                            ("La legislación que el prestamista acepta como base para el "
                             "establecimiento de relaciones con usted antes de la celebración "
                             "del contrato de crédito.", 602,
                             "Legislación Española.", 602),
                            ("Cláusula sobre la legislación aplicable que rige en relación con "
                             "el contrato de crédito y/o tribunal competente.", 638,
                             "El contrato de Préstamo se regirá e interpretará de conformidad "
                             "con la ley española, incluyendo las disposiciones especiales "
                             "reguladoras del", 638),
                            ("Régimen lingüístico", 670,
                             "La información y los términos contractuales se facilitarán en "
                             "lengua castellana, salvo que lo solicite en otra lengua oficial "
                             "autorizada del Estado", 669),
                        ],
                    ),
                ],
            },
            {
                "type": "section",
                "id": "relativa_recurso",
                "title": "c) Relativa al recurso",
                "y_hint": 687,
                "children": [
                    condiciones_table(
                        "datos_recurso",
                        "Relativa al recurso",
                        698,
                        [
                            ("Existencia o acceso a los procedimientos extrajudiciales de "
                             "reclamación y recurso.", 698,
                             "CaixaBank Payments & Consumer, que no está adherida a la junta "
                             "arbitral de consumo, tiene establecido un Servicio de Atención al "
                             "Cliente del", 698),
                        ],
                    ),
                ],
            },
        ],
    },

    # -----------------------------------------------------------------
    # Page noise: page number, Logalty sidebar metadata, footer.
    # -----------------------------------------------------------------
    {
        "type": "noise",
        "id": "footer_pages_top",
        "text": "28/40",
        "kind": "page_number",
        "y_hint": 269,
    },
    {
        "type": "noise",
        "id": "sidebar_logalty",
        "text": "Logalty Guid: 001001-0001-000000076308655.par - Date: 2022/07/11 T 19:08:36 CEST +0200 - Pages: 28/40",
        "kind": "logalty_metadata",
        "y_hint": 331,
    },
    {
        "type": "noise",
        "id": "footer_pagina",
        "text": "Página 2/2",
        "kind": "page_number",
        "y_hint": 799,
    },
]
