"""Golden structure spec for 25356487E_CONTRATO.pdf page 2 (ASNEF loan financial-conditions page).

CaixaBank Payments & Consumer "Condiciones Particulares": interest rates, total cost,
repayment terms, payment domicile, plus a closing prose/signature block. Generated by
golden-scaffolder, reviewer fixes applied (label/value bbox alignment). Walker-compatible
types only.
"""

PDF = "/Users/carlos/Edelwyss/Projects/docomestria/Dataset/25356487E_CONTRATO.pdf"
PAGE = 2

META = {
    "document_type": "contrato_prestamo_financiacion",
    "annotator": "scaffolder",
    "covers_cases": [
        "inline_kv_in_prose",
        "financial_conditions_block",
        "rate_grid_multicolumn",
        "repeated_signature_columns",
        "asnef_legal_prose",
        "logalty_noise",
    ],
}


STRUCTURE = [
    # Page banner / model header — noise, NOT a section title.
    {"type": "noise", "id": "modelo_header", "text": "Nº Modelo F_AS-5 Hoja nº ......2/25......",
     "kind": "watermark", "y_hint": 22.7},
    {"type": "noise", "id": "titulo_contrato",
     "text": "CONTRATO DE PRÉSTAMO DE FINANCIACIÓN A COMPRADOR DE BIENES MUEBLES",
     "kind": "watermark", "y_hint": 82.8},
    {"type": "prose_block", "id": "modelo_aprobado", "label": "Modelo aprobado",
     "text": "Modelo aprobado a la ASNEF por la Dirección General de los Registros y del Notariado (DGRN) (Resolución de 04/02/2000. Modificado por Resoluciones de DGRN de 23/05/2006, de 29/09/2011, de 02/07/2013, de 23/01/2014, de 07/10/2019 y de 07/06/2021",
     "y_hint": 95.3},

    # Interest-rate grid (multi-column row at y~146-166).
    {"type": "kv_group", "id": "intereses",
     "pairs": [
         {"label": "Tipo deudor", "value": "9,99", "y_hint": 162.4, "x_hint": 99.3},
         {"label": "TAE/ TAE Variable", "value": "11,58", "y_hint": 165.9, "x_hint": 261.6},
         {"label": "Intereses de demora", "value": "11,990", "y_hint": 163.6, "x_hint": 379.7},
         {"label": "Importe intereses de demora", "value": "11.230,11", "y_hint": 163.6, "x_hint": 379.7},
     ]},

    # Cost / amount block.
    {"type": "kv_leaf", "id": "coste_total_prestamo",
     "label": "Coste total del Préstamo para el prestatario", "value": "12.050,92", "y_hint": 192.9},
    {"type": "kv_leaf", "id": "importe_total_adeudado",
     "label": "Importe Total adeudado por el prestatario", "value": "32.830,92", "y_hint": 229.7},
    {"type": "kv_leaf", "id": "penalidad_cuota_impagada",
     "label": "Penalidad por cada cuota impagado", "value": "35", "y_hint": 260.5},
    {"type": "kv_group", "id": "comision_cancelacion",
     "pairs": [
         {"label": "Comisión por cancelación anticipada", "value": "1,00", "y_hint": 273.8, "x_hint": 206.8},
         {"label": "Comisión cancelación (terminación < 1 año)", "value": "0,500", "y_hint": 273.8, "x_hint": 359.3},
     ]},
    {"type": "kv_leaf", "id": "importe_diario_desistimiento",
     "label": "Importe diario derecho de desistimiento", "value": "NO APLICA", "y_hint": 315.6},

    # Reconocimiento de deuda (inline KVs within prose).
    {"type": "kv_group", "id": "reconocimiento_deuda",
     "pairs": [
         {"label": "Número de plazos", "value": "108", "y_hint": 347.5, "x_hint": 122.4},
         {"label": "Importe de cada plazo", "value": "303,99", "y_hint": 348.7, "x_hint": 163.3},
     ]},

    # Domicilio de pago. Entity + address share one fused span at y=380.6;
    # labels use real on-page prefixes ("Entidad", "con domicilio en") so the
    # linker isolates each value bbox within the line (f01, f04).
    {"type": "kv_leaf", "id": "domicilio_pago_entidad",
     "label": "Entidad", "value": "BANCO BILBAO VIZCAYA ARGENTARIA",
     "y_hint": 380.6, "label_x_hint": 27.0, "x_hint": 148.0},
    {"type": "kv_leaf", "id": "domicilio_pago_direccion",
     "label": "con domicilio en", "value": "AV. TENOR FLETA, 55",
     "y_hint": 380.6, "label_x_hint": 280.0, "x_hint": 340.0},
    {"type": "kv_leaf", "id": "domicilio_pago_localidad",
     "label": "Localidad", "value": "ZARAGOZA-TENOR FLETA - ZA", "y_hint": 396.5, "label_x_hint": 127.7},
    {"type": "kv_leaf", "id": "domicilio_pago_cuenta",
     "label": "Nº de cuenta", "value": "ES12 0182 6908 9502 0154 3190", "y_hint": 396.5, "x_hint": 380.0},

    # Closing legal prose.
    {"type": "prose_block", "id": "derecho_desistimiento", "label": "Derecho de desistimiento",
     "text": "Derecho de desistimiento. (Art. 9.4 de la Ley de Venta a Plazos de Bienes Muebles y art. 28 de la Ley de Contratos de Crédito al Consumo según Condición General 13).",
     "y_hint": 456.3},
    {"type": "section", "id": "duracion_contrato",
     "title": "Duración del contrato – (ver anexo I) Cuadro de amortización del contrato",
     "y_hint": 481.5,
     "children": [
         {"type": "prose_block", "id": "declaracion_intervinientes", "label": "Declaración de los intervinientes",
          "text": "Los intervinientes, caso de ser consumidores a los efectos de la Ley de Contratos de crédito al consumo, declaran haber recibido la información previa al contrato y la explicación personalizada, con la debida antelación y a su satisfacción, en los términos exigidos en la misma. Los abajo firmantes conocen y aceptan el contenido de las Condiciones Particulares y Generales del presente contrato, del que declaran haber recibido la correspondiente copia.",
          "y_hint": 494.2},
         # f02: label repointed to the prose line at y=557.4 (real on-page prefix)
         # so the linker no longer grabs the Financiador 'En FUENLABRADA' cell.
         {"type": "kv_leaf", "id": "num_hojas",
          "label": "firman las partes el presente contrato en", "value": "24 hojas", "y_hint": 557.4},
     ]},

    # Signature columns — three parties. f03/f05: each pair carries a real label
    # prefix ("En" / "Fecha") plus label_x_hint so the label bbox lands in its
    # own column instead of all sharing the Financiador cell.
    {"type": "kv_group", "id": "lugar_fecha_firma",
     "pairs": [
         {"label": "En", "value": "FUENLABRADA", "y_hint": 575.7, "label_x_hint": 27.0, "x_hint": 43.0},
         {"label": "En", "value": "FUENLABRADA", "y_hint": 575.7, "label_x_hint": 280.7, "x_hint": 297.0},
         {"label": "En", "value": "FUENLABRADA", "y_hint": 575.7, "label_x_hint": 409.0, "x_hint": 425.0},
         {"label": "Fecha", "value": "11-07-2022", "y_hint": 594.8, "label_x_hint": 27.0, "x_hint": 57.0},
         {"label": "Fecha", "value": "11-07-2022", "y_hint": 594.8, "label_x_hint": 280.7, "x_hint": 310.0},
         {"label": "Fecha", "value": "11-07-2022", "y_hint": 594.8, "label_x_hint": 409.0, "x_hint": 439.0},
     ]},
    {"type": "signature_placeholder", "id": "firma_prestatario",
     "label": "Prestatario/s", "value": "", "y_hint": 614.4},
    {"type": "signature_placeholder", "id": "firma_fiador",
     "label": "Fiador/es", "value": "", "y_hint": 614.4},
    {"type": "signature_placeholder", "id": "firma_financiador",
     "label": "Financiador", "value": "", "y_hint": 614.4},

    # Footer / legal noise.
    {"type": "noise", "id": "logalty_metadata",
     "text": "Logalty Guid: 001001-0001-000000076308655.par - Date: 2022/07/11 T 19:08:36 CEST +0200 - Pages: 2/40",
     "kind": "logalty_metadata", "y_hint": 271.9},
    {"type": "noise", "id": "nota_anexos",
     "text": "(1) Si son varios deberá utilizarse anexo II, (2) Si son varios deberá utilizarse anexo II, (3) Si son varios deberá utilizarse anexo II",
     "kind": "sidebar", "y_hint": 733.6},
    {"type": "prose_block", "id": "datos_financiador", "label": "Datos del financiador",
     "text": "Datos del financiador: CaixaBank Payments & Consumer, E.F.C., E.P., S.A.U., domiciliada en Calle Caleruega, 102, de (28033) Madrid, CIF A-08980153- Inscrita en el Registro Mercantil de Madrid, Tomo 36.556, Folio 29, Hoja M-656.492 e inscrita con el nº 8776 en el Registro de Establecimientos de Crédito del Banco de España.",
     "y_hint": 751.7},
    {"type": "noise", "id": "footer_mod",
     "text": "MOD. (M)006-720.0313-02 (21) - 24 de mayo de 2022",
     "kind": "page_number", "y_hint": 789.1},
    {"type": "noise", "id": "footer_reverso",
     "text": "REVERSO SÓLO APTO PARA LA IMPRESIÓN DE LAS CONDICIONES PARTICULARES CONTENIDAS EN EL B. O. E., SEGÚN RESOLUCIONES REFERIDAS EN EL ENCABEZAMIENTO DEL CONTRATO",
     "kind": "sidebar", "y_hint": 791.9},
]
