"""Golden structure spec for 42646161K_CONTRATO.pdf page 14 (14/22).

CaixaBank ASNEF auto-loan (F_AS-5). INE/SECCI standardized credit-info form,
page 2/4: a 2-column label/value table (left = generic concept/explanation,
right = the specific contract value or descriptive clause) grouped into
thematic blocks — payment modality, importe total, objeto financiado,
garantías, prelación de pagos, "3. Costes del crédito" (TIN, TAE, seguro
obligatorio, servicios accesorios) and the "Costes relacionados" tail.
Generated by golden-scaffolder. Walker-compatible types only.
"""

import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))


def _condiciones_table_x(table_id, title, y_hint, rows):
    """2-col label/value table; row may carry a value x_hint.

    Row tuple: (label, label_y, value, value_y[, value_x]).
    When value_x is present the value cell is a 3-tuple so the walker
    disambiguates the value column from the label column (needed where the
    value atom shares a y-band with the label or where the binary X marker
    must be pinned to a specific x).
    """
    out_rows = []
    for r in rows:
        label = (r[0], r[1])
        value = (r[2], r[3], r[4]) if len(r) >= 5 and r[4] is not None else (r[2], r[3])
        out_rows.append({"label": label, "value": value})
    return {
        "type": "table",
        "id": table_id,
        "title": title,
        "y_hint": y_hint,
        "columns": [
            {"id": "label", "label": "Concepto", "type": "text"},
            {"id": "value", "label": "Valor", "type": "text"},
        ],
        "rows": out_rows,
    }


PDF = "/Users/carlos/Edelwyss/Projects/docomestria/Dataset/42646161K_CONTRATO.pdf"
PAGE = 14

META = {
    "document_type": "informacion_normalizada_europea_credito_consumo",
    "annotator": "scaffolder",
    "covers_cases": [
        "secci_two_column_label_value_table",
        "multiline_value_fusion",
        "binary_checkbox_x_value",
        "amount_euros_value",
        "percentage_value",
        "unfilled_form_slot_blank",
        "thematic_subsections",
        "logalty_sidebar_noise",
        "value_x_hint_disambiguation",
    ],
}


STRUCTURE = [
    # -----------------------------------------------------------------
    # Modalidad de pago / payment-installment block (tail from prior page,
    # left column "Los plazos y, en su caso, el orden...").
    # The three 230,87 amounts are the cuota values.
    # -----------------------------------------------------------------
    _condiciones_table_x(
        "modalidad_pago",
        "Modalidad de pago a plazos",
        72,
        [
            ("Los plazos y, en su caso, el orden en que se realizarán los pagos a plazos.", 72,
             "Modalidad de pago a plazos para el Préstamo AUTO: La primera de 230,87 euros, "
             "la última de 230,87 euros y las restantes de 230,87 euros, si bien se tendrán "
             "en cuenta las siguientes excepcionalidades:", 72, 151.1),
            # f01: value now anchored at the amount span (4.698,67, x=242.8, y=250.0)
            # so geometry matchers land on the real value, not the bullet-label fragment.
            ("Importe intereses y/o gastos que deberá pagar el consumidor de la manera siguiente:", 234,
             "4.698,67 euros. (En caso de Cuenta de Crédito, incluida la que lo sea con "
             "Disponibilidad Restringida, estos intereses hacen referencia a la primera "
             "disposición ya efectuada).", 250, 242.8),
            # f02: value anchored at the amount span (389,85, x=264.6, y=271.3).
            ("• Importe Comisión de apertura:", 271,
             "389,85 euros, que se pagará: financiada, incluyéndose en el importe del crédito "
             "concedido.", 271, 264.6),
            # f03: dotted placeholder — amount field is BLANK in the PDF. Unfilled
            # form slot, value stays empty (the prior 'euros, que se pagará:' was a
            # template stub sliced out of the label span).
            ("• Importe Comisión de estudio:", 293,
             "", 293),
        ],
    ),

    # -----------------------------------------------------------------
    # Importe Total / Importe total que deberá usted pagar.
    # -----------------------------------------------------------------
    _condiciones_table_x(
        "importe_total",
        "Importe total que deberá usted pagar",
        317,
        [
            ("Importe total que deberá usted pagar. Es decir, el importe del capital prestado "
             "más los intereses y posibles gastos relacionados con su crédito.", 318,
             "Importe Total: 19.393,08 euros.", 317, 151.8),
        ],
    ),

    # -----------------------------------------------------------------
    # Objeto Financiado / forma de pago diferido.
    # -----------------------------------------------------------------
    _condiciones_table_x(
        "objeto_financiado",
        "Objeto Financiado",
        356,
        [
            ("El crédito se concede en forma de pago diferido por un bien o servicio o está "
             "relacionado con el suministro de bienes específicos o con la prestación de un "
             "servicio. Nombre del producto/servicio Precio al contado", 356,
             "Objeto Financiado TURISMO", 356, 151.1),
            ("Importe del bien/servicio al contado", 392,
             "14.995,00 euros (IVA/IGIC incluido)", 392, 267.8),
        ],
    ),

    # -----------------------------------------------------------------
    # Tipo de Garantía (checkbox: Garantía personal / Reserva de dominio).
    # -----------------------------------------------------------------
    _condiciones_table_x(
        "tipo_garantia",
        "Tipo de Garantía",
        420,
        [
            ("Garantías requeridas. Descripción de la garantía que usted ofrece en relación "
             "con el contrato de crédito.", 422,
             "Tipo de Garantía: Garantía personal Reserva de dominio", 420, 151.1),
        ],
    ),

    # -----------------------------------------------------------------
    # Prelación de pagos / reembolsos.
    # -----------------------------------------------------------------
    _condiciones_table_x(
        "prelacion_pagos",
        "Prelación de pagos",
        463,
        [
            # f04: full fused text now includes 'por CaixaBank Payments & Consumer'
            # after 'suplidos' (was truncated).
            ("Los reembolsos no suponen la inmediata amortización del capital", 463,
             "Todos los pagos recibidos serán aplicados con la siguiente prelación: (i) costas "
             "y gastos suplidos por CaixaBank Payments & Consumer; (ii) comisiones devengadas; "
             "(iii) penalidades (penas e intereses de demora incluidos); (iv) intereses "
             "ordinarios; (v) capital del Préstamo.", 463, 151.1),
        ],
    ),

    # -----------------------------------------------------------------
    # Section 3 — Costes del crédito
    # -----------------------------------------------------------------
    {
        "type": "section",
        "id": "costes_credito",
        "title": "3. Costes del crédito",
        "y_hint": 487,
        "children": [
            _condiciones_table_x(
                "costes_credito_tabla",
                "Costes del crédito",
                501,
                [
                    ("El tipo deudor o, si ha lugar, los diferentes tipos deudores que se "
                     "aplican al contrato de crédito.", 502,
                     "Tipo de interés Nominal del Préstamo Mercantil, del Préstamo AUTO, o de "
                     "la primera disposición de la Cuenta de Crédito en modalidad de pago "
                     "“Fraccionado”: 8,99 % anual (tipo fijo).", 501, 151.1),
                    ("Tasa anual equivalente (TAE). La TAE es el coste total del crédito "
                     "expresado en forma de porcentaje anual del importe total del crédito. "
                     "La TAE sirve para comparar diferentes ofertas.", 558,
                     "TAE del Préstamo Mercantil, del Préstamo AUTO o de la primera "
                     "disposición de la Cuenta de Crédito en modalidad de pago "
                     "“Fraccionado”: 10,40 %", 558, 151.1),
                    ("¿Es obligatorio para obtener el crédito en sí, o en las condiciones "
                     "ofrecidas, - tomar una póliza de seguros que garantice el crédito, u - "
                     "otro servicio accesorio? Si los costes de estos servicios no son "
                     "conocidos del prestamista, no se incluyen en la TAE.", 609,
                     "Sí, es obligatoria la contratación del seguro.", 617, 196.1),
                ],
            ),
        ],
    },

    # -----------------------------------------------------------------
    # Costes relacionados (block header + carry-over text).
    # -----------------------------------------------------------------
    _condiciones_table_x(
        "costes_relacionados",
        "Costes relacionados",
        711,
        [
            ("Para mantener una o varias cuentas se requiere registrar tanto las "
             "transacciones de pago como la disposición del crédito.", 725,
             "En caso de Cuenta de Crédito (sea o no con Disposición Restringida), el "
             "crédito sólo puede ser dispuesto por el titular para adeudo de las cantidades "
             "recibidas directamente, mediante la Tarjeta - si la ha concedido CaixaBank "
             "Payments & Consumer- o a través de otros medios que le permitan disponer del "
             "mismo (crédito). También se adeudará en la Cuenta de Crédito abierta al "
             "titular cualquier suma a cargo de éste en concepto de intereses, comisiones, "
             "gastos, indemnizaciones o cualquier otro que derive del contrato.", 725, 151.1),
        ],
    ),

    # -----------------------------------------------------------------
    # Page noise: top page marker, Logalty sidebar metadata, footer MOD.
    # -----------------------------------------------------------------
    {
        "type": "noise",
        "id": "footer_pages_top",
        "text": "Pages: 14/22",
        "kind": "page_number",
        "y_hint": 300,
    },
    {
        "type": "noise",
        "id": "sidebar_logalty",
        "text": "Logalty Guid: 001001-0001-000000040208342.par - Date: 2020/01/27 T 14:22:49 CET +0100",
        "kind": "logalty_metadata",
        "y_hint": 444,
    },
    {
        "type": "noise",
        "id": "footer_pagina",
        "text": "MOD. (M) 006-720.0511-90 (08) - 23 de octubre de 2019 - Página 2/4",
        "kind": "page_number",
        "y_hint": 780,
    },
]
