"""Golden structure spec for 42646161K_CONTRATO.pdf page 13.

First page (1/4) of the INE standardized European consumer-credit form:
- Banner: INFORMACIÓN NORMALIZADA EUROPEA (INE) (noise/watermark)
- Place/date/Nº solicitud header row (kv_group)
- Section 1. Identidad y detalles de contacto del prestamista/intermediario (KVs)
- Section 2. Descripción de las características principales del producto de crédito
  - Tipo de crédito checklist (X = Préstamo AUTO + Cuenta de Crédito)
  - Long descriptive prose about Cuenta de Crédito / Préstamo Mercantil
  - 2-col label/value table: Importe total / Condiciones disposición / Duración / Pagos
    (mostly empty form slots; filled: 13.384,85 importe, 84 meses duración)
- Logalty sidebar metadata + footer noise

Generated by golden-scaffolder. Walker-compatible types only.
"""

PDF = "/Users/carlos/Edelwyss/Projects/docomestria/Dataset/42646161K_CONTRATO.pdf"
PAGE = 13

META = {
    "document_type": "Información Normalizada Europea (INE) sobre el crédito al consumo (CaixaBank Payments & Consumer)",
    "annotator": "scaffolder",
    "covers_cases": [
        "ine_banner_watermark",
        "ine_lugar_fecha_solicitud_header",
        "ine_seccion_1_identidad_prestamista_kv",
        "ine_seccion_2_tipo_credito_checklist",
        "ine_caracteristicas_prose_block",
        "ine_importe_duracion_2col_table_with_empty_slots",
        "caixabank_logalty_sidebar_noise",
    ],
}


STRUCTURE = [
    {
        "type": "noise",
        "id": "banner_ine",
        "text": "INFORMACIÓN NORMALIZADA EUROPEA (INE) SOBRE EL CRÉDITO AL CONSUMO",
        "kind": "watermark",
        "y_hint": 77,
    },
    {
        "type": "kv_group",
        "id": "lugar_fecha_solicitud",
        "pairs": [
            {"label": "En", "value": "TELDE", "y_hint": 112, "x_hint": 27.0},
            {"label": "a", "value": "27", "y_hint": 112, "x_hint": 186.9},
            {"label": "de", "value": "Enero", "y_hint": 112, "x_hint": 215.3},
            {"label": "de", "value": "2020", "y_hint": 112, "x_hint": 268.9},
            {"label": "Nº SOLICITUD", "value": "202001450115298", "y_hint": 112, "x_hint": 318.9},
        ],
    },
    {
        "type": "prose_block",
        "id": "nota_sombreado",
        "label": "Nota sombreado",
        "text": "Las informaciones resaltadas con sombreado en este INE son especialmente relevantes.",
        "y_hint": 133,
    },
    {
        "type": "section",
        "id": "identidad_contacto",
        "title": "1. Identidad y detalles de contacto del prestamista y/o del intermediario",
        "y_hint": 149,
        "children": [
            {
                "type": "kv_leaf",
                "id": "prestamista",
                "label": "Prestamista",
                "value": "CaixaBank Payments & Consumer, E.F.C., E.P., S.A.U., (en adelante, CaixaBank Payments & Consumer)",
                "y_hint": 164,
            },
            {
                "type": "kv_leaf",
                "id": "prestamista_direccion",
                "label": "Dirección",
                "value": "C/ Caleruega, 102 28033 Madrid",
                "y_hint": 175,
            },
            {
                "type": "kv_leaf",
                "id": "prestamista_web",
                "label": "Dirección de página web",
                "value": "www.caixabankpc.com",
                "y_hint": 185,
            },
            {
                "type": "kv_leaf",
                "id": "intermediario",
                "label": "Intermediario del crédito",
                "value": "GRUPO MIGUEL LEON S.L.",
                "y_hint": 207,
            },
            {
                "type": "kv_leaf",
                "id": "intermediario_direccion",
                "label": "Dirección",
                "value": "callejon del castillo ,Nº 215 , 35200 TELDE",
                "y_hint": 217,
            },
        ],
    },
    {
        "type": "section",
        "id": "caracteristicas_producto",
        "title": "2. Descripción de las características principales del producto de crédito",
        "y_hint": 236,
        "children": [
            {
                "type": "kv_leaf",
                "id": "tipo_credito",
                "label": "Tipo de crédito",
                "value": 'X Contrato de Financiación a Comprador de Vehículos ("Préstamo AUTO") y Cuenta de Crédito',
                "y_hint": 297,
            },
            {
                "type": "prose_block",
                "id": "tipo_credito_descripcion",
                "label": "Descripción Cuenta de Crédito / Préstamo Mercantil",
                "text": (
                    "La Cuenta de Crédito permitirá a su titular realizar disposiciones del saldo "
                    "disponible en la modalidad “Revolving” (reintegro, total o parcial, del importe "
                    "dispuesto, incrementando el disponible hasta el límite concedido). Estas disposiciones "
                    "podrán efectuarse mediante una tarjeta de crédito emitida por CaixaBank Payments & "
                    "Consumer a nombre de su titular (Tarjeta). Cuando se contrate un Préstamo Mercantil o un "
                    "Préstamo AUTO conjuntamente con una Cuenta de Crédito con Disposición Restringida, "
                    "CaixaBank Payments & Consumer podrá, posteriormente, permitir al titular disfrutar del "
                    "saldo disponible de la Cuenta de Crédito. La financiación propuesta regula las relaciones "
                    "entre el Titular (usted), de una parte, y CaixaBank Payments & Consumer, de otra, respecto "
                    "de la concesión de la misma (financiación) a usted, por el importe indicado en este INE, "
                    "para financiar la compra de bienes y/o contratación de servicios."
                ),
                "y_hint": 315,
            },
            {
                "type": "table",
                "id": "caracteristicas_importe_duracion",
                "title": "Características del crédito",
                "y_hint": 566,
                "columns": [
                    {"id": "label", "label": "Característica", "type": "text"},
                    {"id": "value", "label": "Detalle", "type": "text"},
                ],
                "rows": [
                    {
                        "label": ("Importe del Préstamo Mercantil/AUTO:", 566),
                        "value": ("13.384,85", 566, 285.8),
                    },
                    {
                        "label": ("Importe Cuenta de Crédito – Primera disposición", 575),
                        "value": ("euros", 575, 317.9),
                    },
                    {
                        "label": ("Límite", 575),
                        "value": ("euros", 575, 416.6),
                    },
                    {
                        "label": ("Condiciones que rigen la disposición del crédito.", 615),
                        "value": (
                            "CaixaBank Payments & Consumer abonará directamente al establecimiento "
                            "comercial, por cuenta del titular, el importe de las compras o servicios "
                            "adquiridos mediante el préstamo/crédito, tras el estudio previo, la "
                            "aprobación de la solicitud del mismo, y la recepción de la documentación "
                            "requerida.",
                            615,
                        ),
                    },
                    {
                        "label": ("Duración del contrato de crédito", 689),
                        "value": ("84 meses.", 689, 424.0),
                    },
                    {
                        "label": ("Los plazos y, en su caso, el orden en que se realizarán los pagos a plazos.", 719),
                        "value": ("Deberá usted pagar lo siguiente:", 717),
                    },
                    {
                        "label": ("Modalidad de pago a plazos para Préstamo Mercantil", 745),
                        "value": (
                            "La primera de ............. euros, la última de ............... euros y las "
                            "restantes de ................. euros, si bien se tendrán en cuenta las "
                            "siguientes excepcionalidades:",
                            753,
                        ),
                    },
                ],
            },
        ],
    },
    # --- Logalty sidebar / footer noise --------------------------------------
    {
        "type": "noise",
        "id": "barcode_solicitud",
        "text": "202001450115298",
        "kind": "watermark",
        "y_hint": 56,
    },
    {
        "type": "noise",
        "id": "sidebar_pages",
        "text": "Pages: 13/22",
        "kind": "logalty_metadata",
        "y_hint": 300,
    },
    {
        "type": "noise",
        "id": "sidebar_cet",
        "text": "CET +0100",
        "kind": "logalty_metadata",
        "y_hint": 372,
    },
    {
        "type": "noise",
        "id": "sidebar_time",
        "text": "14:22:49",
        "kind": "logalty_metadata",
        "y_hint": 391,
    },
    {
        "type": "noise",
        "id": "sidebar_date",
        "text": "2020/01/27 T",
        "kind": "logalty_metadata",
        "y_hint": 444,
    },
    {
        "type": "noise",
        "id": "sidebar_date_label",
        "text": "Date:",
        "kind": "logalty_metadata",
        "y_hint": 497,
    },
    {
        "type": "noise",
        "id": "sidebar_guid",
        "text": "Guid: 001001-0001-000000040208342.par",
        "kind": "logalty_metadata",
        "y_hint": 689,
    },
    {
        "type": "noise",
        "id": "sidebar_logalty",
        "text": "Logalty",
        "kind": "logalty_metadata",
        "y_hint": 718,
    },
    {
        "type": "noise",
        "id": "footer_mod",
        "text": "MOD. (M) 006-720.0511-90 (08) - 23 de octubre de 2019 - Página 1/4",
        "kind": "page_number",
        "y_hint": 803,
    },
    {
        "type": "signature_placeholder",
        "id": "firma",
        "label": "FIRMA",
        "value": "",
        "y_hint": 760,
    },
]
