"""Golden structure spec for 43631720F_CONTRATO.pdf page 14 (F_AS-5).

CaixaBank ASNEF auto-loan — standardized INE/SECCI credit information form
(continuation). Two-column layout: left = explanatory labels, right = filled
values + legal prose. Section "3. Costes del crédito" begins mid-page.

Generated by golden-scaffolder. Walker-compatible types only.
"""

PDF = "/Users/carlos/Edelwyss/Projects/docomestria/Dataset/43631720F_CONTRATO.pdf"
PAGE = 14

META = {
    "document_type": "prestamo_auto_secci",
    "annotator": "scaffolder",
    "covers_cases": [
        "secci_credit_form",
        "dotted_fill_value",
        "checkbox_selected_x",
        "two_column_label_prose",
        "section_costes_credito",
        "footer_logalty_sidebar",
    ],
}


STRUCTURE = [
    # --- Modalidad de pago a plazos / cuenta de crédito ---
    {
        "type": "kv_group",
        "id": "modalidad_pago_plazos",
        "pairs": [
            {"label": "Modalidad de pago a plazos para el Préstamo AUTO - primera",
             "value": "283,66", "y_hint": 81, "x_hint": 205.6},
            {"label": "Modalidad de pago a plazos para el Préstamo AUTO - última",
             "value": "283,66", "y_hint": 81, "x_hint": 283.7},
            {"label": "Modalidad de pago a plazos para el Préstamo AUTO - restantes",
             "value": "283,66", "y_hint": 81, "x_hint": 382.0},
        ],
    },
    {
        "type": "kv_group",
        "id": "modalidad_pago_cuenta_credito",
        "pairs": [
            {"label": "Primera disposición: Importe", "value": "", "y_hint": 131},
            {"label": "Modalidad de pago", "value": "Fraccionado (Fr)", "y_hint": 138, "x_hint": 223.6},
        ],
    },
    {
        "type": "prose_block",
        "id": "prose_cuenta_credito",
        "label": "Devolución del crédito de Cuenta de Crédito",
        "text": "En caso de Cuenta de Crédito, excepto en la modalidad de pago "
                "“Fin de Mes”, el titular deberá pagar mensualmente la cantidad "
                "acordada en concepto de cuota mensual, así como aquellos otros "
                "importes que conforme a lo pactado correspondan, y siempre "
                "respetando el límite de crédito autorizado.",
        "y_hint": 153,
    },
    # --- Importe intereses y/o gastos ---
    {
        "type": "section",
        "id": "importe_intereses_gastos",
        "title": "Importe intereses y/o gastos que deberá pagar el consumidor de la manera siguiente:",
        "y_hint": 234,
        "children": [
            {"type": "kv_leaf", "id": "importe_intereses", "label": "Importe Intereses",
             "value": "7.066,28", "y_hint": 250, "x_hint": 242.8},
            {"type": "kv_group", "id": "comision_apertura",
             "pairs": [
                 {"label": "Importe Comisión de apertura", "value": "507,00", "y_hint": 271, "x_hint": 264.6},
                 {"label": "Comisión de apertura - forma de pago",
                  "value": "financiada, incluyéndose en el importe del crédito concedido",
                  "y_hint": 280, "x_hint": 366.7},
             ]},
            {"type": "kv_leaf", "id": "comision_estudio", "label": "Importe Comisión de estudio",
             "value": "", "y_hint": 293},
        ],
    },
    # --- Importe Total ---
    {
        "type": "kv_leaf",
        "id": "importe_total",
        "label": "Importe Total",
        "value": "27.231,36 euros.",
        "y_hint": 318,
        "x_hint": 212.6,
    },
    # --- Objeto Financiado ---
    {
        "type": "kv_group",
        "id": "objeto_financiado",
        "pairs": [
            {"label": "Objeto Financiado", "value": "TURISMO", "y_hint": 357, "x_hint": 204.2},
            {"label": "Importe del bien/servicio al contado",
             "value": "16.900,00 euros (IVA/IGIC incluido)", "y_hint": 392, "x_hint": 267.8},
        ],
    },
    # --- Tipo de Garantía ---
    {
        "type": "kv_group",
        "id": "tipo_garantia",
        "pairs": [
            {"label": "Garantía personal", "value": "", "y_hint": 429, "x_hint": 175.6},
            {"label": "Reserva de dominio", "value": "", "y_hint": 437, "x_hint": 175.6},
        ],
    },
    {
        "type": "prose_block",
        "id": "prelacion_pagos",
        "label": "Prelación de pagos",
        "text": "Todos los pagos recibidos serán aplicados con la siguiente prelación: "
                "(i) costas y gastos suplidos por CaixaBank Payments & Consumer; "
                "(ii) comisiones devengadas; (iii) penalidades (penas e intereses de "
                "demora incluidos); (iv) intereses ordinarios; (v) capital del Préstamo.",
        "y_hint": 463,
    },
    # --- Section 3. Costes del crédito ---
    {
        "type": "section",
        "id": "costes_credito",
        "title": "3. Costes del crédito",
        "y_hint": 488,
        "children": [
            {"type": "kv_leaf", "id": "tin_fraccionado",
             "label": "Tipo de interés Nominal del Préstamo AUTO / primera disposición (Fraccionado)",
             "value": "8,99 % anual (tipo fijo).", "y_hint": 510, "x_hint": 229.0},
            {"type": "kv_leaf", "id": "tin_cuenta_credito",
             "label": "Tipo de Interés Nominal de la Cuenta de Crédito",
             "value": "", "y_hint": 517},
            {"type": "kv_leaf", "id": "tae",
             "label": "TAE del Préstamo AUTO / primera disposición de la Cuenta de Crédito",
             "value": "10,29 %", "y_hint": 567, "x_hint": 182.7},
            {"type": "kv_leaf", "id": "tae_cuenta_credito",
             "label": "TAE de la Cuenta de Crédito",
             "value": "", "y_hint": 574},
            {"type": "kv_group", "id": "seguro_obligatorio",
             "pairs": [
                 {"label": "¿Es obligatorio tomar una póliza de seguros? - No",
                  "value": "X", "y_hint": 618, "x_hint": 156.4},
             ]},
            {"type": "kv_group", "id": "objeto_asociado_suministro",
             "pairs": [
                 {"label": "Objeto financiado asociado a contratos de suministro - No",
                  "value": "X", "y_hint": 667, "x_hint": 156.4},
             ]},
        ],
    },
    {
        "type": "prose_block",
        "id": "costes_relacionados",
        "label": "Costes relacionados",
        "text": "En caso de Cuenta de Crédito (sea o no con Disposición Restringida), "
                "el crédito sólo puede ser dispuesto por el titular para adeudo de las "
                "cantidades recibidas directamente, mediante la Tarjeta - si la ha "
                "concedido CaixaBank Payments & Consumer- o a través de otros medios "
                "que le permitan disponer del mismo (crédito).",
        "y_hint": 725,
    },
    # --- Noise: page header, footer, Logalty sidebar ---
    {
        "type": "noise",
        "id": "logalty_metadata",
        "text": "Logalty Guid: 001001-0001-000000036424941.par - Date: 2019/09/24 T 20:10:19 CEST +0200 - Pages: 14/22",
        "kind": "logalty_metadata",
        "y_hint": 269,
    },
    {
        "type": "noise",
        "id": "footer_mod",
        "text": "MOD. (M) 006-720.0511-90 (07) - 17 de julio de 2019 - Página 2/4",
        "kind": "page_number",
        "y_hint": 780,
    },
]
