"""Golden structure spec for 43631720F_CONTRATO.pdf page 2 (CaixaBank ASNEF auto-loan, F_AS-5).

Reverse side: two-column "CONDICIONES GENERALES" legal prose (clauses 1-14 covering
interest, TAE, early repayment, debt recognition, insurance, withdrawal, assignment),
a three-column signature row, and footer/sidebar noise.
Generated by golden-scaffolder. Walker-compatible types only.
"""

PDF = "/Users/carlos/Edelwyss/Projects/docomestria/Dataset/43631720F_CONTRATO.pdf"
PAGE = 2

META = {
    "document_type": "prestamo_financiacion_auto",
    "annotator": "scaffolder",
    "covers_cases": [
        "condiciones_generales_prose",
        "two_column_legal_clauses",
        "contract_header_banner",
        "three_column_signature_row",
        "page_footer_noise",
        "logalty_sidebar_metadata",
    ],
}


STRUCTURE = [
    # --- Header banner (noise: page-top contract identification) ---
    {
        "type": "noise",
        "id": "banner_condiciones_generales",
        "text": "CONDICIONES GENERALES",
        "kind": "watermark",
        "y_hint": 35.4,
    },
    {
        "type": "noise",
        "id": "banner_contrato",
        "text": "Contrato de préstamo de financiación a comprador, impreso nº 4026707 "
                "celebrado entre CAIXABANK PAYMENTS & CONSUMER, E.F.C., E.P., S.A.U. "
                "(también CaixaBank Payments & Consumer) y D/Dª EVA LINARES REB",
        "kind": "watermark",
        "y_hint": 50.4,
    },

    # --- Legal clauses 1-14 (two-column prose) ---
    {
        "type": "prose_block",
        "id": "clausula_01_prestatarios",
        "label": "1) PRESTATARIOS",
        "text": "Para el caso de intervenir varios prestatarios se obligan con carácter "
                "solidario al cumplimiento de las obligaciones dimanantes del presente contrato.",
        "y_hint": 77.9,
    },
    {
        "type": "prose_block",
        "id": "clausula_02_fiadores",
        "label": "2) FIADORES",
        "text": "El/los fiadores afianzan solidariamente entre sí, y con igual carácter "
                "respecto al deudor/es principal/es, el cumplimiento de todas las obligaciones "
                "asumidas por el mismo en este contrato con renuncia expresa a los beneficios "
                "de orden, división y excusión.",
        "y_hint": 110.1,
    },
    {
        "type": "prose_block",
        "id": "clausula_03_objeto",
        "label": "3) OBJETO",
        "text": "El presente contrato, de naturaleza mercantil, tiene por objeto la concesión "
                "de un préstamo de financiación para la adquisición del objeto identificado en "
                "las condiciones particulares de este contrato.",
        "y_hint": 150.5,
    },
    {
        "type": "prose_block",
        "id": "clausula_04_domicilio",
        "label": "4) DOMICILIO",
        "text": "Se establece a los efectos prevenidos en la Ley 28/1998, que el lugar donde "
                "hayan de efectuarse las notificaciones, requerimientos y emplazamientos es el "
                "domicilio consignado para cada parte en las condiciones particulares de este "
                "contrato, quedando obligadas las partes a comunicarse fehacientemente, "
                "cualquier cambio del mismo, sin perjuicio de lo establecido en la citada ley, "
                "comunicándolo mediante escrito dirigido al Registrador de Venta a Plazos. "
                "Igualmente se señala como domicilio de verificación de pago el de la "
                "domiciliación bancaria señalada en las condiciones particulares.",
        "y_hint": 182.6,
    },
    {
        "type": "prose_block",
        "id": "clausula_05_mora_pago",
        "label": "5) MORA EN EL PAGO",
        "text": "Los deudores que demoren el pago de sus deudas vencidas, deberán satisfacer "
                "desde el día siguiente a su vencimiento un interés moratorio pactado, que se "
                "devengará día a día, sin necesidad de requerimiento, aplicándose la fórmula del "
                "interés simple: I= C x R x T : 100.",
        "y_hint": 264.0,
    },
    {
        "type": "prose_block",
        "id": "clausula_06_incumplimiento",
        "label": "6) INCUMPLIMIENTO, VENCIMIENTO ANTICIPADO Y DOCUMENTACIÓN DE LA DEUDA",
        "text": "La falta de pago de dos cualesquiera de los plazos, o del último de ellos, a "
                "que se hace referencia en el epígrafe RECONOCIMIENTO DE DEUDA facultará al "
                "financiador para dar por vencido el préstamo, extinguiéndose el aplazamiento y "
                "exigiendo, como consecuencia el abono de la totalidad de la deuda pendiente.",
        "y_hint": 369.4,
    },
    {
        "type": "prose_block",
        "id": "clausula_07_reembolso_anticipado",
        "label": "7) REEMBOLSO ANTICIPADO",
        "text": "El prestatario podrá reembolsar anticipadamente el importe del préstamo de "
                "forma total o parcial en cualquier momento, comunicándolo por escrito al "
                "financiador.",
        "y_hint": 458.8,
    },
    {
        "type": "prose_block",
        "id": "clausula_08_calculo_tae",
        "label": "8) CÁLCULO Y ELEMENTOS QUE COMPONEN LA T.A.E.",
        "text": "Se entenderá por tasa anual equivalente el coste total del crédito, expresado "
                "en un porcentaje anual sobre la cuantía del crédito concedido. A efectos "
                "informativos se hace constar que dicha tasa (TAE) se obtiene aplicando la "
                "fórmula contenida en la Ley 16/2011, de 24 de junio, de contratos de crédito al "
                "consumo.",
        "y_hint": 134.3,
    },
    {
        "type": "prose_block",
        "id": "clausula_09_prohibicion_enajenar",
        "label": "9) PROHIBICIÓN DE ENAJENAR",
        "text": "El prestatario no podrá enajenar o gravar el objeto financiado adquirido hasta "
                "el completo pago del préstamo sin autorización expresa del financiador.",
        "y_hint": 223.6,
    },
    {
        "type": "prose_block",
        "id": "clausula_10_reserva_dominio",
        "label": "10) RESERVA DE DOMINIO",
        "text": "El dominio del objeto financiado pertenece al Financiador hasta el completo "
                "pago del mismo.",
        "y_hint": 255.7,
    },
    {
        "type": "prose_block",
        "id": "clausula_11_autorizacion_pago",
        "label": "11) AUTORIZACIÓN DE PAGO",
        "text": "El prestatario autoriza al financiador a entregar el importe del préstamo al "
                "vendedor, siendo el presente contrato la carta de autorización más eficaz.",
        "y_hint": 279.7,
    },
    {
        "type": "prose_block",
        "id": "clausula_12_seguros",
        "label": "12) SEGUROS",
        "text": "El comprador deberá suscribir y mantener durante la vigencia de este contrato, "
                "o de sus prórrogas, un seguro a todo riesgo, sobre el bien cuya adquisición se "
                "financia, que cubra los daños propios del mismo, incluyéndose los supuestos de "
                "incendio y robo. Se designa como primer beneficiario de la indemnización del "
                "seguro al financiador.",
        "y_hint": 311.8,
    },
    {
        "type": "prose_block",
        "id": "clausula_13_desistimiento",
        "label": "13) FACULTAD DE DESISTIMIENTO",
        "text": "a) Derecho de desistimiento recogido en la Ley de Venta a Plazos: Conforme a lo "
                "establecido en el art. 9 de la Ley de Venta a Plazos de Bienes Muebles, en el "
                "supuesto en que el prestatario tuviera la condición de consumidor podrá "
                "ejercitar la facultad de desistimiento. b) Derecho de desistimiento recogido en "
                "la Ley de contratos de crédito al consumo: dispondrá de un plazo de catorce días "
                "naturales para desistir del presente contrato sin indicación de los motivos ni "
                "penalización alguna.",
        "y_hint": 409.6,
    },
    {
        "type": "prose_block",
        "id": "clausula_14_cesion",
        "label": "14) CESIÓN",
        "text": "El financiador se reserva el derecho a ceder a tercero los derechos y acciones "
                "derivados del presente contrato, así como la reserva de dominio constituida a su "
                "favor y cualquier otra garantía formalizada con ocasión del presente contrato, "
                "comunicando esta cesión al prestatario.",
        "y_hint": 693.7,
    },

    # --- Signature row (three columns) ---
    {
        "type": "signature_placeholder",
        "id": "firma_prestatarios",
        "label": "Prestatario/s",
        "value": "",
        "y_hint": 766.9,
    },
    {
        "type": "signature_placeholder",
        "id": "firma_fiadores",
        "label": "Fiador/es",
        "value": "",
        "y_hint": 766.9,
    },
    {
        "type": "signature_placeholder",
        "id": "firma_financiador",
        "label": "Financiador",
        "value": "",
        "y_hint": 766.9,
    },

    # --- Footer / sidebar noise ---
    {
        "type": "noise",
        "id": "modelo_hoja",
        "text": "Nº Modelo F_AS-5 Hoja nº ......2/11......",
        "kind": "page_number",
        "y_hint": 24.5,
    },
    {
        "type": "noise",
        "id": "footer_reverso",
        "text": "REVERSO SÓLO APTO PARA LA IMPRESIÓN DE LAS CONDICIONES GENERALES DE ESTE "
                "CONTRATO",
        "kind": "watermark",
        "y_hint": 808.1,
    },
    {
        "type": "noise",
        "id": "footer_modelo",
        "text": "MOD. (M) 006-720.0313-02 (16) - 17 de julio de 2019",
        "kind": "watermark",
        "y_hint": 808.1,
    },
    {
        "type": "noise",
        "id": "sidebar_logalty",
        "text": "Logalty Guid: 001001-0001-000000036424941.par - Date: 2019/09/24 T 20:10:19 "
                "CEST +0200 - Pages: 2/22",
        "kind": "logalty_metadata",
        "y_hint": 271.9,
    },
]
