"""Golden structure spec for 43631720F_CONTRATO.pdf page 13 (INE standardized
European credit information form — CaixaBank Payments & Consumer auto loan).

Page 13/22: identity of lender/intermediary (section 1) + product description
with credit-type selection and key economic fields (section 2). Mostly legal
prose with a handful of populated form values.

Generated by golden-scaffolder. Walker-compatible types only.
"""

PDF = "/Users/carlos/Edelwyss/Projects/docomestria/Dataset/43631720F_CONTRATO.pdf"
PAGE = 13

META = {
    "document_type": "ine_credito_consumo",
    "annotator": "scaffolder",
    "covers_cases": [
        "ine_header_banner_noise",
        "lender_intermediary_identity_kv",
        "credit_type_checkbox_selection",
        "legal_prose_blocks",
        "economic_form_slots_partial_fill",
        "logalty_sidebar_noise",
    ],
}


STRUCTURE = [
    {
        "type": "noise",
        "id": "banner_ine",
        "text": "INFORMACIÓN NORMALIZADA EUROPEA (INE) SOBRE EL CRÉDITO AL CONSUMO",
        "kind": "watermark",
        "y_hint": 77,
    },
    {
        "type": "noise",
        "id": "barcode_solicitud",
        "text": "201909231266092",
        "kind": "watermark",
        "y_hint": 56,
    },
    {
        "type": "kv_group",
        "id": "cabecera_lugar_fecha",
        "pairs": [
            {"label": "En", "value": "GIRONA", "y_hint": 112, "x_hint": 27.0},
            {"label": "a", "value": "24", "y_hint": 112, "x_hint": 186.9},
            {"label": "de", "value": "Septiembre", "y_hint": 112, "x_hint": 215.3},
            {"label": "de", "value": "2019", "y_hint": 112, "x_hint": 268.9},
            {"label": "Nº SOLICITUD", "value": "201909231266092", "y_hint": 112, "x_hint": 318.9},
        ],
    },
    {
        "type": "section",
        "id": "identidad_prestamista",
        "title": "1. Identidad y detalles de contacto del prestamista y/o del intermediario",
        "y_hint": 149,
        "children": [
            {
                "type": "kv_group",
                "id": "datos_prestamista",
                "pairs": [
                    {
                        "label": "Prestamista",
                        "value": "CaixaBank Payments & Consumer, E.F.C., E.P., S.A.U., (en adelante, CaixaBank Payments & Consumer)",
                        "y_hint": 164,
                    },
                    {"label": "Dirección", "value": "C/ Caleruega, 102 28033 Madrid", "y_hint": 175},
                    {"label": "Dirección de página web", "value": "www.caixabankpc.com", "y_hint": 185},
                ],
            },
            {
                "type": "kv_group",
                "id": "datos_intermediario",
                "pairs": [
                    {"label": "Intermediario del crédito", "value": "GARAGE ANDREU S.A.", "y_hint": 208},
                    {
                        "label": "Dirección",
                        "value": "ANTONI BARNES I GULTRESA ,Nº 8 , POL.IND. MAS XIRGU 17005 GIRONA",
                        "y_hint": 218,
                    },
                ],
            },
        ],
    },
    {
        "type": "section",
        "id": "caracteristicas_producto",
        "title": "2. Descripción de las características principales del producto de crédito",
        "y_hint": 236,
        "children": [
            {
                "type": "kv_leaf",
                "id": "tipo_credito_seleccionado",
                "label": "Tipo de crédito",
                "value": 'X Contrato de Financiación a Comprador de Vehículos ("Préstamo AUTO") y Cuenta de Crédito',
                "y_hint": 297,
            },
            {
                "type": "prose_block",
                "id": "prose_cuenta_credito",
                "label": "Funcionamiento de la Cuenta de Crédito",
                "text": "La Cuenta de Crédito permitirá a su titular realizar disposiciones del saldo disponible en la modalidad Revolving (reintegro, total o parcial, del importe dispuesto, incrementando el disponible hasta el límite concedido). Estas disposiciones podrán efectuarse mediante una tarjeta de crédito emitida por CaixaBank Payments & Consumer a nombre de su titular (Tarjeta).",
                "y_hint": 315,
            },
            {
                "type": "prose_block",
                "id": "prose_disposicion_restringida",
                "label": "Disposición restringida y préstamo asociado",
                "text": "No obstante, si la Cuenta de Crédito se contrata con Disposición Restringida solo podrá ser dispuesta para la adquisición del/de los objeto/s financiado/s sin mediación o uso de tarjeta. Cuando se contrate un Préstamo Mercantil o un Préstamo AUTO conjuntamente con una Cuenta de Crédito, la activación de la Tarjeta quedará supeditada a la voluntad del titular y a la autorización de CaixaBank Payments & Consumer.",
                "y_hint": 370,
            },
            {
                "type": "prose_block",
                "id": "prose_financiacion_propuesta",
                "label": "Relaciones de la financiación propuesta",
                "text": "La financiación propuesta regula las relaciones entre el Titular (usted), de una parte, y CaixaBank Payments & Consumer, de otra, respecto de la concesión de la misma a usted, por el importe indicado en este INE, para financiar la compra de bienes y/o contratación de servicios.",
                "y_hint": 457,
            },
            {
                "type": "kv_group",
                "id": "importe_total_credito",
                "pairs": [
                    {
                        "label": "Importe del Préstamo Mercantil/AUTO",
                        "value": "17.407,00",
                        "y_hint": 566,
                        "x_hint": 285.8,
                    },
                    {"label": "Importe Cuenta de Crédito – Primera disposición", "value": "", "y_hint": 575},
                    {"label": "Límite", "value": "", "y_hint": 575},
                ],
            },
            {
                "type": "kv_group",
                "id": "duracion_contrato",
                "pairs": [
                    {
                        "label": "Duración del contrato de crédito (número de mensualidades Préstamo Mercantil/AUTO)",
                        "value": "96 meses.",
                        "y_hint": 689,
                        "x_hint": 424.0,
                    },
                ],
            },
            {
                "type": "kv_group",
                "id": "modalidad_pago_plazos",
                "pairs": [
                    {"label": "Cuotas mensuales totales (modalidad Fraccionado)", "value": "", "y_hint": 731},
                    {"label": "La primera de (euros)", "value": "", "y_hint": 753},
                    {"label": "la última de (euros)", "value": "", "y_hint": 753},
                    {"label": "las restantes de (euros)", "value": "", "y_hint": 753},
                ],
            },
        ],
    },
    {
        "type": "noise",
        "id": "page_number",
        "text": "13/22",
        "kind": "page_number",
        "y_hint": 269,
    },
    {
        "type": "noise",
        "id": "logalty_sidebar",
        "text": "Logalty Guid: 001001-0001-000000036424941.par - Date: 2019/09/24 T 20:10:19 CEST +0200",
        "kind": "logalty_metadata",
        "y_hint": 691,
    },
    {
        "type": "noise",
        "id": "footer_mod",
        "text": "MOD. (M) 006-720.0511-90 (07) - 17 de julio de 2019 - Página 1/4",
        "kind": "page_number",
        "y_hint": 803,
    },
]
