"""Golden structure spec for 43631720F_CONTRATO.pdf page 1.

ASNEF model F_AS-5 vehicle-loan cover page (CaixaBank Payments & Consumer):
intervinientes (comprador-prestatario, fiador, financiador, vendedor), objeto a
financiar, economic conditions, reconocimiento de deuda, domicilio de pago and
firmas. Same family as 25356487E. Generated by golden-scaffolder.
"""

PDF = "/Users/carlos/Edelwyss/Projects/docomestria/Dataset/43631720F_CONTRATO.pdf"
PAGE = 1

META = {
    "document_type": "Contrato de préstamo de financiación a comprador de bienes muebles",
    "annotator": "scaffolder",
    "covers_cases": [
        "asnef_vehicle_loan_cover",
        "person_inline_name_columns",
        "fiador_block_empty",
        "financiador_block",
        "objeto_a_financiar",
        "economic_conditions_inline",
        "reconocimiento_de_deuda",
        "domicilio_de_pago",
        "firmas_tri_columna",
    ],
}


STRUCTURE = [
    {"type": "noise", "id": "banner_modelo", "text": "Nº Modelo F_AS-5",
     "kind": "watermark", "y_hint": 24.5},
    {"type": "noise", "id": "hoja_num", "text": "Hoja nº ......1/11......",
     "kind": "page_number", "y_hint": 33.6},
    {"type": "noise", "id": "banner_contrato",
     "text": "CONTRATO DE PRÉSTAMO DE FINANCIACIÓN A COMPRADOR DE BIENES MUEBLES",
     "kind": "watermark", "y_hint": 82.1},
    {"type": "noise", "id": "sidebar_logalty",
     "text": "Logalty Guid: 001001-0001-000000036424941.par - Date: 2019/09/24 T 20:10:19 CEST +0200 - Pages: 1/22",
     "kind": "logalty_metadata", "y_hint": 271.9},

    {"type": "section", "id": "encabezado", "title": "Encabezado", "y_hint": 61.8,
     "children": [
        {"type": "kv_leaf", "id": "nro_contrato", "label": "Nº",
         "value": "201909231266092", "y_hint": 55.7},
        {"type": "prose_block", "id": "modelo_aprobado", "label": "Modelo aprobado",
         "text": "Modelo aprobado a la ASNEF por la Dirección General de los Registros y del "
                 "Notariado (DGRN). Resolución de 04/02/2000. Modificado por Resoluciones de "
                 "DGRN de 23/05/2006, de 29/09/2011 y de 02/07/2013",
         "y_hint": 92.3},
        {"type": "kv_leaf", "id": "impreso_nro", "label": "IMPRESO Nº",
         "value": "4026707", "y_hint": 115.6},
     ]},

    {"type": "section", "id": "comprador_prestatario",
     "title": "DATOS PERSONALES O DENOMINACIÓN SOCIAL, EN SU CASO, DEL COMPRADOR-PRESTATARIO (1)",
     "y_hint": 127.4,
     "children": [
        {"type": "kv_group", "id": "comprador_datos", "pairs": [
            {"label": "1er Apellido", "value": "LINARES", "y_hint": 146.8, "x_hint": 100.0},
            {"label": "2º Apellido", "value": "REBOLLO", "y_hint": 146.8, "x_hint": 213.7},
            {"label": "Nombre", "value": "EVA", "y_hint": 146.8, "x_hint": 327.7},
            {"label": "NIF/CIF", "value": "43631720F", "y_hint": 146.8, "x_hint": 444.6},
            {"label": "Domicilio", "value": "GARRINADA,36 PISO 2 - OLOT < GERONA >", "y_hint": 162.5},
            {"label": "Tel", "value": "655740201", "y_hint": 161.3, "x_hint": 398.2},
            {"label": "Correo electrónico", "value": "LINARESREIXACH@OUTLOOK.COM", "y_hint": 172.9, "x_hint": 286.3},
            {"label": "Inscrita en", "value": "", "y_hint": 173.2},
            {"label": "Y en su nombre", "value": "", "y_hint": 184.5},
        ]},
     ]},

    {"type": "section", "id": "fiador",
     "title": "DATOS PERSONALES O DENOMINACIÓN SOCIAL, EN SU CASO, DEL FIADOR (2)",
     "y_hint": 202.1,
     "children": [
        {"type": "kv_group", "id": "fiador_datos", "pairs": [
            {"label": "1er Apellido", "value": "", "y_hint": 212.2, "x_hint": 96.3},
            {"label": "2º Apellido", "value": "", "y_hint": 212.2, "x_hint": 207.2},
            {"label": "Nombre", "value": "", "y_hint": 212.2, "x_hint": 322.6},
            {"label": "NIF/CIF", "value": "", "y_hint": 212.2, "x_hint": 443.0},
            {"label": "Domicilio", "value": "", "y_hint": 237.2},
            {"label": "Tel", "value": "", "y_hint": 236.0, "x_hint": 398.2},
            {"label": "Correo electrónico", "value": "", "y_hint": 247.6, "x_hint": 286.3},
            {"label": "Inscrita en", "value": "", "y_hint": 247.6},
            {"label": "Y en su nombre", "value": "", "y_hint": 258.9},
        ]},
     ]},

    {"type": "section", "id": "financiador", "title": "FINANCIADOR", "y_hint": 276.4,
     "children": [
        {"type": "kv_group", "id": "financiador_datos", "pairs": [
            {"label": "Financiador",
             "value": "CAIXABANK PAYMENTS & CONSUMER, E.F.C., E.P., S.A.U.", "y_hint": 276.4},
            {"label": "D. (representante)", "value": "LUIS LAGARES PUIG", "y_hint": 276.4, "x_hint": 480.0},
            {"label": "NIF", "value": "35063208F", "y_hint": 288.0},
            {"label": "con poder otorgado ante notario de", "value": "BARCELONA",
             "y_hint": 288.9, "x_hint": 108.8},
            {"label": "D.", "value": "TOMAS GIMENEZ DUART", "y_hint": 288.9, "x_hint": 327.2},
            {"label": "con fecha", "value": "12-02-2013", "y_hint": 288.9, "x_hint": 456.9},
        ]},
     ]},

    {"type": "section", "id": "vendedor",
     "title": "VENDEDOR/ INTERMEDIARIO FINANCIERO", "y_hint": 300.5,
     "children": [
        {"type": "kv_group", "id": "vendedor_datos", "pairs": [
            {"label": "Vendedor/Intermediario financiero", "value": "GARAGE ANDREU S.A.",
             "y_hint": 300.5},
            {"label": "Domicilio social",
             "value": "ANTONI BARNES I GULTRESA ,Nº 8 , POL.IND. MAS XIRGU 17005 GIRONA",
             "y_hint": 312.2},
        ]},
     ]},

    {"type": "section", "id": "objeto_a_financiar", "title": "OBJETO A FINANCIAR (3)",
     "y_hint": 323.6,
     "children": [
        {"type": "kv_group", "id": "objeto_datos", "pairs": [
            {"label": "Objeto a financiar", "value": "TURISMO", "y_hint": 323.6, "x_hint": 27.0},
            {"label": "Marca", "value": "CITROEN", "y_hint": 323.6, "x_hint": 294.4},
            {"label": "Modelo", "value": "BERLINGO DIESEL", "y_hint": 323.6, "x_hint": 414.6},
            {"label": "Nº fabricación o chasis", "value": "VR7ECYHYCKJ740498", "y_hint": 335.1, "x_hint": 27.0},
            {"label": "Matrícula (en su caso)", "value": "4235KZJ", "y_hint": 335.1, "x_hint": 253.5},
        ]},
     ]},

    {"type": "section", "id": "condiciones_economicas", "title": "Condiciones económicas",
     "y_hint": 351.6,
     "children": [
        {"type": "kv_group", "id": "importes_base", "pairs": [
            {"label": "Precio de compraventa (valor contado)", "value": "16.900,00€",
             "y_hint": 351.3, "x_hint": 506.3},
            {"label": "Desembolso inicial, (en su caso)", "value": "0,00€",
             "y_hint": 361.7, "x_hint": 528.7},
            {"label": "Capital inicial del préstamo.", "value": "16.900,00€€",
             "y_hint": 373.3, "x_hint": 501.2},
        ]},

        {"type": "table", "id": "comisiones",
         "title": "Espacio reservado para incluir las comisiones, gastos etc.",
         "y_hint": 385.1,
         "columns": [
             {"id": "tipo", "label": "Tipo", "type": "text"},
             {"id": "comision_apertura", "label": "Comisión apertura", "type": "amount"},
             {"id": "comision_estudio", "label": "Comisión Estudio", "type": "amount"},
         ],
         "rows": [
             {"tipo": ("Financiadas", 396.7), "comision_apertura": ("507,00€", 396.4, 221.3),
              "comision_estudio": ("0,00€", 396.4, 417.1)},
             {"tipo": ("No Financiadas", 405.7), "comision_apertura": ("", 405.7),
              "comision_estudio": ("", 405.7)},
         ]},

        {"type": "table", "id": "servicios_accesorios",
         "title": "Espacio reservado para Servicios accesorios relacionados (mantenimiento, seguros, etc.)",
         "y_hint": 425.1,
         "columns": [
             {"id": "tipo", "label": "Tipo", "type": "text"},
             {"id": "coste_seguro_mensual", "label": "Coste del seguro mensual", "type": "amount"},
         ],
         "rows": [
             {"tipo": ("Condicionantes", 436.7), "coste_seguro_mensual": ("", 436.7)},
             {"tipo": ("No Condicionantes", 445.4), "coste_seguro_mensual": ("28,73€", 445.1, 226.4)},
         ]},

        {"type": "kv_leaf", "id": "importe_total_prestamo",
         "label": "Importe Total del Préstamo (Capital+Otros conceptos financiados)",
         "value": "17.407,00€", "y_hint": 456.5, "x_hint": 506.3},

        {"type": "kv_group", "id": "intereses", "pairs": [
            {"label": "Interés deudor fijo", "value": "8,99%anual", "y_hint": 479.8, "x_hint": 174.2},
            {"label": "TAE/TAE Variable", "value": "10,29 %", "y_hint": 479.8, "x_hint": 174.2},
            {"label": "Intereses de demora", "value": "10,990 %anual", "y_hint": 479.4, "x_hint": 380.1},
            {"label": "Intereses de demora importe", "value": "7.066,28€", "y_hint": 479.4, "x_hint": 454.5},
        ]},

        {"type": "kv_leaf", "id": "coste_total_prestamo",
         "label": "Coste total del Préstamo para el prestatario",
         "value": "7.573,28€", "y_hint": 500.9, "x_hint": 185.3},
        {"type": "kv_leaf", "id": "importe_total_adeudado",
         "label": "Importe Total adeudado por el prestatario",
         "value": "24.473,28€", "y_hint": 527.4, "x_hint": 506.3},

        {"type": "kv_leaf", "id": "penalidad_cuota_impagada",
         "label": "Penalidad por cada cuota impagado",
         "value": "30€ (se cobrará una sola vez para cada cuota)", "y_hint": 548.7},
        {"type": "kv_leaf", "id": "comision_cancelacion_anticipada",
         "label": "Comisión por cancelación anticipada",
         "value": "1,00 % de la deuda cancelada ( 0,500 % si para la terminación del contrato queda menos de un año)",
         "y_hint": 556.6, "x_hint": 178.8},
        {"type": "kv_leaf", "id": "importe_diario_desistimiento",
         "label": "Importe diario derecho de desistimiento",
         "value": "4,34€", "y_hint": 568.3, "x_hint": 305.2},
     ]},

    {"type": "section", "id": "reconocimiento_deuda",
     "title": "RECONOCIMIENTO DE DEUDA", "y_hint": 580.6,
     "children": [
        {"type": "prose_block", "id": "reconocimiento_texto", "label": "Reconocimiento de deuda",
         "text": "RECONOCIMIENTO DE DEUDA: El prestatario reconoce deber al financiador la cantidad de "
                 "24.473,28€ que se pagarán en 96 plazos de 254,93€ cada uno, con los vencimientos "
                 "que se detallan en el cuadro de amortización.",
         "y_hint": 580.6},
     ]},

    {"type": "section", "id": "domicilio_pago",
     "title": "DOMICILIO DE PAGO", "y_hint": 603.5,
     "children": [
        {"type": "kv_group", "id": "domicilio_pago_datos", "pairs": [
            {"label": "Entidad", "value": "CAIXABANK, S.A.", "y_hint": 603.5},
            {"label": "con domicilio en", "value": "AV. LES TRIES, 8", "y_hint": 604.6, "x_hint": 313.8},
            {"label": "Localidad", "value": "LA RODONA - GERONA", "y_hint": 614.1, "x_hint": 155.2},
            {"label": "Nº de cuenta", "value": "ES90 2100 3724 1321 0049 6694", "y_hint": 615.0, "x_hint": 346.6},
        ]},
     ]},

    {"type": "prose_block", "id": "duracion_y_conformidad", "label": "Duración y conformidad",
     "text": "Duración del contrato – (ver anexo I) Cuadro de amortización del contrato. Los "
             "intervinientes, caso de ser consumidores a los efectos de la Ley de Contratos de "
             "crédito al consumo, declaran haber recibido la información previa al contrato y la "
             "explicación personalizada, con la debida antelación y a su satisfacción, en los "
             "términos exigidos en la misma. Los abajo firmantes conocen y aceptan el contenido de "
             "las Condiciones Particulares y Generales del presente contrato, del que declaran "
             "haber recibido la correspondiente copia. En prueba de conformidad, firman las partes "
             "el presente contrato en 11 hojas y en 1 ejemplar/es",
     "y_hint": 658.1},

    {"type": "section", "id": "firmas", "title": "Firmas", "y_hint": 706.3,
     "children": [
        {"type": "kv_group", "id": "firma_prestatario", "pairs": [
            {"label": "En", "value": "GIRONA", "y_hint": 706.3, "x_hint": 27.0},
            {"label": "Fecha", "value": "24-09-2019", "y_hint": 716.3, "x_hint": 27.0},
        ]},
        {"type": "signature_placeholder", "id": "firma_prestatario_box",
         "label": "Prestatario/s", "value": "", "y_hint": 728.1},
        {"type": "kv_group", "id": "firma_fiador", "pairs": [
            {"label": "En", "value": "GIRONA", "y_hint": 706.3, "x_hint": 280.7, "label_x_hint": 280.7},
            {"label": "Fecha", "value": "24-09-2019", "y_hint": 716.3, "x_hint": 280.7, "label_x_hint": 280.7},
        ]},
        {"type": "signature_placeholder", "id": "firma_fiador_box",
         "label": "Fiador/es", "value": "", "y_hint": 728.1},
        {"type": "kv_group", "id": "firma_financiador", "pairs": [
            {"label": "En", "value": "GIRONA", "y_hint": 706.3, "x_hint": 409.0, "label_x_hint": 409.0},
            {"label": "Fecha", "value": "24-09-2019", "y_hint": 716.3, "x_hint": 409.0, "label_x_hint": 409.0},
        ]},
        {"type": "signature_placeholder", "id": "firma_financiador_box",
         "label": "Financiador", "value": "", "y_hint": 728.1},
     ]},

    {"type": "prose_block", "id": "datos_financiador", "label": "Datos del financiador",
     "text": "Datos del financiador: CaixaBank Payments & Consumer, E.F.C., E.P., S.A.U., "
             "domiciliada en Calle Caleruega, 102, de (28033) Madrid, CIF A-08980153- "
             "Inscrita en el Registro Mercantil de Madrid, Tomo 36.556, Folio 29, Hoja "
             "M-656.492 e inscrita con el nº 8776 en el Registro de Establecimientos de "
             "Crédito del Banco de España.",
     "y_hint": 781.5},

    {"type": "noise", "id": "footer_mod",
     "text": "MOD. (M)006-720.0313-02 (16) - 17 de julio de 2019",
     "kind": "watermark", "y_hint": 789.1},
    {"type": "noise", "id": "footer_reverso",
     "text": "REVERSO SÓLO APTO PARA LA IMPRESIÓN DE LAS CONDICIONES GENERALES CONTENIDAS EN EL B. O. E.",
     "kind": "watermark", "y_hint": 803.2},
]
