"""Golden structure spec for CONTRATO IKEA.pdf page 13.

Continuation page describing payment modalities:
- Intro prose (iv) Cuadro resumen
- 4-col table comparing Fin de Mes / Pago Aplazado (Revolving) / Pago Fraccionado
- Section 2.2 Retirada de dinero en efectivo (prose)
- Section 3. INTERESES (header + prose)
- Sidebar noise: Pages metadata, timestamps, Guid, Logalty, PAG

Generated by golden-scaffolder. Walker-compatible types only.
"""

PDF = "/Users/carlos/Edelwyss/Projects/docomestria/Dataset/CONTRATO IKEA.pdf"
PAGE = 13

META = {
    "document_type": "Contrato de cuenta de crédito con o sin Tarjeta IKEA (CaixaBank Payments & Consumer)",
    "annotator": "scaffolder",
    "covers_cases": [
        "caixabank_ikea_modalidades_pago_4col_table",
        "caixabank_ikea_intro_prose_then_table",
        "caixabank_ikea_subsection_2_2_retirada_efectivo",
        "caixabank_ikea_section_3_intereses_header",
        "caixabank_ikea_logalty_sidebar_noise",
    ],
}


STRUCTURE = [
    {
        "type": "prose_block",
        "id": "intro_cuadro_resumen",
        "label": "(iv) Cuadro resumen",
        "text": (
            "(iv) Cuadro resumen: En el siguiente cuadro le resumimos las "
            "características de cada una de estas modalidades:"
        ),
        "y_hint": 70,
    },
    {
        "type": "table",
        "id": "modalidades_pago",
        "title": "Modalidades de pago — Cuadro resumen",
        "y_hint": 112,
        "columns": [
            {"id": "modalidad", "label": "Modalidad de devolución", "type": "text"},
            {"id": "momento", "label": "Momento del pago", "type": "text"},
            {"id": "importe", "label": "Importe del pago", "type": "text"},
            {"id": "intereses", "label": "¿Genera intereses o costes específicos?", "type": "text"},
        ],
        "rows": [
            {
                "modalidad": ("Fin de Mes", 148),
                "momento": ("Al final del mes", 148),
                "importe": ("La totalidad del crédito que haya utilizado durante ese mes.", 148),
                "intereses": ("No genera intereses ni costes específicos.", 148),
            },
            {
                "modalidad": ("Pago Aplazado", 201),
                "momento": ("Varios pagos en periodos mensuales sucesivos", 201),
                "importe": ("Se indica en las Condiciones Particulares de este contrato.", 201),
                "intereses": (
                    "Cada operación genera intereses desde el momento en que usted "
                    "la realiza. Además, el reembolso (pago) anticipado genera un precio "
                    "por compensación.",
                    201,
                ),
            },
            {
                "modalidad": ("Pago Fraccionado", 299),
                "momento": (
                    "Una operación concreta puede pagarse en periodos de 3, 6, 10 meses o "
                    "los meses que pudieran ofrecerse en cada caso, si la compra se realiza "
                    "en Establecimientos IKEA (presencial u online) o en los Establecimientos "
                    "cuando así se le haya ofrecido.",
                    299,
                ),
                "importe": (
                    "Es una cuota de cantidad constante que pagará tantas veces como meses "
                    "seleccionados y que comprende tanto intereses (los que se indican en las "
                    "Condiciones Particulares) como parte del importe inicial de la operación "
                    "fraccionada. La última cuota podrá ser de cantidad inferior debido al "
                    "ajuste por decimales.",
                    299,
                ),
                "intereses": (
                    "Puede generar intereses y también le podemos cobrar un precio por el servicio.",
                    299,
                ),
            },
        ],
    },
    {
        "type": "section",
        "id": "retirada_efectivo",
        "title": "2.2 Retirada de dinero en efectivo.",
        "y_hint": 506,
        "children": [
            {
                "type": "prose_block",
                "id": "retirada_efectivo_prose",
                "label": "Descripción retirada efectivo",
                "text": (
                    "Además de pagar a crédito, la Tarjeta IKEA permite retirar (sacar) "
                    "dinero en efectivo a crédito. Podrá hacerlo en cajeros automáticos. "
                    "El precio del servicio es el que se ha informado en las Condiciones "
                    "Particulares de este contrato. En la Condición General «ACCESOS Y USOS»"
                ),
                "y_hint": 527,
            },
        ],
    },
    {
        "type": "section",
        "id": "intereses",
        "title": "3. INTERESES.",
        "y_hint": 590,
        "children": [
            {
                "type": "kv_leaf",
                "id": "intereses_subtitulo",
                "label": "Cómo se calculan los intereses y cuándo se pagan.",
                "value": "",
                "y_hint": 600,
            },
            {
                "type": "prose_block",
                "id": "intereses_3_1",
                "label": "3.1 Generación de intereses",
                "text": (
                    "3.1 Como indicamos en la Condición General «MODALIDADES DE PAGO Y DE "
                    "RETIRADA DE DINERO O EFECTIVO METÁLICO QUE PERMITA SU Cuenta de Crédito "
                    "CON O SIN Tarjeta IKEA », los pagos que usted o el Beneficiario realicen "
                    "con cargo a la Cuenta de crédito con o sin la Tarjeta IKEA, cuando se "
                    "trate de modalidad de pago Fin de Mes no generan intereses si los abona "
                    "íntegramente a final del período de liquidación (a final de mes)."
                ),
                "y_hint": 621,
            },
            {
                "type": "prose_block",
                "id": "intereses_aplazado_fraccionado",
                "label": "Intereses Pago Aplazado y Fraccionado",
                "text": (
                    "Sí generan intereses los pagos que realice con su Cuenta de crédito con "
                    "o sin Tarjeta IKEA si tiene activada la modalidad de Pago Aplazado "
                    "(Revolving) o mediante Pago Fraccionado (*), esos intereses se generan "
                    "desde la fecha en que usted o el Beneficiario realiza las Operaciones "
                    "(compras) y se cobran el día que usted ha elegido para realizar el pago "
                    "mensualmente."
                ),
                "y_hint": 694,
            },
        ],
    },
    # --- Sidebar/footer noise -------------------------------------------------
    {
        "type": "noise",
        "id": "sidebar_pages",
        "text": "Pages: 13/59",
        "kind": "logalty_metadata",
        "y_hint": 301,
    },
    {
        "type": "noise",
        "id": "sidebar_cet",
        "text": "CET +0100",
        "kind": "logalty_metadata",
        "y_hint": 373,
    },
    {
        "type": "noise",
        "id": "sidebar_time",
        "text": "20:07:05",
        "kind": "logalty_metadata",
        "y_hint": 392,
    },
    {
        "type": "noise",
        "id": "sidebar_date",
        "text": "2025/02/25 T",
        "kind": "logalty_metadata",
        "y_hint": 445,
    },
    {
        "type": "noise",
        "id": "sidebar_date_label",
        "text": "Date:",
        "kind": "logalty_metadata",
        "y_hint": 497,
    },
    {
        "type": "noise",
        "id": "sidebar_guid",
        "text": "Guid: 001001-0001-000000136441990.par",
        "kind": "logalty_metadata",
        "y_hint": 690,
    },
    {
        "type": "noise",
        "id": "sidebar_logalty",
        "text": "Logalty",
        "kind": "logalty_metadata",
        "y_hint": 718,
    },
    {
        "type": "noise",
        "id": "footer_pag",
        "text": "PAG 5/31",
        "kind": "page_number",
        "y_hint": 798,
    },
]
