"""Golden structure spec for PATRIMONIAL.pdf page 3 (CGPJ Punto Neutro Judicial
asset-investigation report: INSS Tarjeta Social Digital prestaciones query for a titular).

Generated by golden-scaffolder. Walker-compatible types only.
"""

PDF = "/Users/carlos/Edelwyss/Projects/docomestria/Dataset/AZUREDOCUI/2_Example/PATRIMONIAL .pdf"
PAGE = 3

META = {
    "document_type": "averiguacion_patrimonial",
    "annotator": "scaffolder",
    "covers_cases": [
        "section_with_kv_group",
        "empty_form_slot_value",
        "status_kv_leaf",
        "page_footer_noise",
        "legal_disclaimer_prose",
    ],
}


STRUCTURE = [
    {
        "type": "noise",
        "id": "banner_cabecera",
        "text": "PLATAFORMA DE SERVICIOS DEL PUNTO NEUTRO JUDICIAL Consulta Integral Patrimonio",
        "kind": "watermark",
        "y_hint": 36,
    },
    {
        "type": "section",
        "id": "inss_consulta_prestaciones",
        "title": "INSS - Consulta Prestaciones Tarjeta Social Digital",
        "y_hint": 112,
        "children": [
            {
                "type": "kv_group",
                "id": "titular",
                "pairs": [
                    {"label": "Nombre", "value": "GHEORGHE ADRIAN", "y_hint": 153},
                    {"label": "Primer apellido", "value": "OPREA", "y_hint": 173},
                    {"label": "Segundo apellido", "value": "---", "y_hint": 193},
                    {"label": "Teléfono", "value": "631723839", "y_hint": 213},
                ],
            },
            {
                "type": "kv_leaf",
                "id": "resultado_prestaciones",
                "label": "Resultado",
                "value": "Sin Prestaciones",
                "y_hint": 233,
            },
        ],
    },
    {
        "type": "prose_block",
        "id": "aviso_legal",
        "label": "Aviso legal",
        "text": (
            "La información obtenida a través del Punto Neutro Judicial únicamente puede "
            "utilizarse en casos permitidos por el ordenamiento jurídico. Dicha información, "
            "cuando se refiera a dato de diciembre, de Protección de Datos y Garantía de "
            "Derechos Digitales. El personal que acc información deberá realizarse respetando "
            "las correspondientes medidas de seguridad que gar"
        ),
        "y_hint": 771,
    },
    {
        "type": "noise",
        "id": "footer_fecha",
        "text": "17/04/26 17:13",
        "kind": "logalty_metadata",
        "y_hint": 806,
    },
    {
        "type": "noise",
        "id": "footer_pagina",
        "text": "Página 3 de 4",
        "kind": "page_number",
        "y_hint": 806,
    },
]
