"""Golden structure spec for PATRIMONIAL.pdf page 4 (PNJ asset-investigation, empty result page).

Punto Neutro Judicial "Consulta Integral Patrimonio" — Entidades Financieras by NIF.
The product table has a header but no data rows; an info notice states responses are
still pending. No key-value data on this page — modelled as section + empty table +
prose notice + legal disclaimer + footer noise.

Generated by golden-scaffolder. Walker-compatible types only.
"""

PDF = "/Users/carlos/Edelwyss/Projects/docomestria/Dataset/AZUREDOCUI/2_Example/PATRIMONIAL .pdf"
PAGE = 4

META = {
    "document_type": "averiguacion_patrimonial_pnj",
    "annotator": "scaffolder",
    "covers_cases": [
        "empty_result_table",
        "table_header_no_rows",
        "pending_response_notice",
        "legal_disclaimer_prose",
    ],
}


STRUCTURE = [
    {
        "type": "noise",
        "id": "banner_consulta",
        "text": "Consulta Integral Patrimonio",
        "kind": "watermark",
        "y_hint": 51,
    },
    {
        "type": "section",
        "id": "entidades_financieras",
        "title": "Entidades Financieras - Consultas por NIF",
        "y_hint": 112,
        "children": [
            {
                "type": "table",
                "id": "lista_productos",
                "title": "Lista de productos",
                "y_hint": 133,
                "columns": [
                    {"id": "iban", "label": "IBAN", "type": "text"},
                    {"id": "entidad", "label": "Entidad", "type": "text"},
                    {"id": "producto", "label": "Producto", "type": "text"},
                    {"id": "fecha_apertura", "label": "Fecha apertura", "type": "text"},
                    {"id": "tipo_intervencion", "label": "Tipo intervención", "type": "text"},
                    {"id": "saldo", "label": "Saldo", "type": "text"},
                    {"id": "divisa", "label": "Divisa", "type": "text"},
                    {"id": "fecha_valor", "label": "Fecha valor", "type": "text"},
                ],
                "rows": [],
            },
            {
                "type": "prose_block",
                "id": "aviso_pendiente",
                "label": "Aviso solicitud pendiente",
                "text": (
                    "Su solicitud a las entidades financieras está realizada pero faltan "
                    "entidades por responder. Podrá ver las respuestas accediendo a la "
                    "pantalla del listado de consultas a EEFF."
                ),
                "y_hint": 178,
            },
        ],
    },
    {
        "type": "prose_block",
        "id": "aviso_legal",
        "label": "Aviso legal",
        "text": (
            "La información obtenida a través del Punto Neutro Judicial únicamente puede "
            "utilizarse en el marco del procedimiento judicial correspondiente, sin que "
            "pueda comunicarse a terceros fuera de los casos permitidos por el "
            "ordenamiento jurídico. Dicha información, cuando se refiera a datos "
            "personales, está sometida al Reglamento General de Protección de Datos y la "
            "Ley Orgánica 3/2018, de 5 de diciembre, de Protección de Datos y Garantía de "
            "Derechos Digitales. El personal que acceda a esta información está sometido "
            "al cumplimiento del deber de secreto. El tratamiento de esta información "
            "deberá realizarse respetando las correspondientes medidas de seguridad que "
            "garanticen su integridad, disponibilidad y confidencialidad."
        ),
        "y_hint": 771,
    },
    {
        "type": "noise",
        "id": "footer_fecha",
        "text": "17/04/26 17:13",
        "kind": "logalty_metadata",
        "y_hint": 806,
    },
    {
        "type": "noise",
        "id": "footer_pagina",
        "text": "Página 4 de 4",
        "kind": "page_number",
        "y_hint": 806,
    },
]
