"""Golden structure spec for PATRIMONIAL.pdf page 1 (Punto Neutro Judicial - Consulta Integral Patrimonio).

Asset-investigation (averiguación patrimonial) report: petition metadata, a table of
consulted services with their results, and the subject's identity data from DGP.
Generated by golden-scaffolder. Walker-compatible types only.
"""

PDF = "/Users/carlos/Edelwyss/Projects/docomestria/Dataset/AZUREDOCUI/2_Example/PATRIMONIAL .pdf"
PAGE = 1

META = {
    "document_type": "averiguacion_patrimonial",
    "annotator": "scaffolder",
    "covers_cases": [
        "petition_metadata_kv",
        "label_value_fused_span",
        "service_result_table",
        "multiline_label_table",
        "person_identity_kv_group",
        "page_banner_noise",
        "legal_footer_prose",
    ],
}


STRUCTURE = [
    # --- Page banner / logo (NOT a section) ---
    {"type": "noise", "id": "banner_pnj", "kind": "watermark",
     "text": "PLATAFORMA DE SERVICIOS DEL PUNTO NEUTRO JUDICIAL", "y_hint": 36},
    {"type": "noise", "id": "banner_titulo", "kind": "watermark",
     "text": "Consulta Integral Patrimonio", "y_hint": 51},

    # --- Datos Petición ---
    {"type": "section", "id": "datos_peticion", "title": "Datos Petición", "y_hint": 112,
     "children": [
        {"type": "kv_leaf", "id": "nro_procedimiento", "label": "Nº Procedimiento",
         "value": "987/2015", "y_hint": 133},
        {"type": "kv_leaf", "id": "nro_documento", "label": "Nº Documento",
         "value": "X6573514E", "y_hint": 153},
        {"type": "kv_leaf", "id": "ejercicio_fiscal", "label": "Ejercicio fiscal",
         "value": "2025", "y_hint": 173},
        {"type": "kv_leaf", "id": "fecha_emision", "label": "Fecha de emisión",
         "value": "17 d’abr. 2026 17:12", "y_hint": 193},
     ]},

    # --- Servicios Consultados (table: service label + result) ---
    {"type": "section", "id": "servicios_consultados", "title": "Servicios Consultados",
     "y_hint": 222, "children": [
        {"type": "table", "id": "servicios_tabla", "title": "Servicios Consultados",
         "y_hint": 241,
         "columns": [
            {"id": "servicio", "label": "Servicio", "type": "text"},
            {"id": "resultado", "label": "Resultado", "type": "text"},
         ],
         "rows": [
            {"servicio": ("AEAT - Consulta Percepciones:", 241),
             "resultado": ("0001 Operación Correcta. No existen datos.", 247)},
            {"servicio": ("AEAT - Consulta Actividades Economicas:", 268),
             "resultado": ("0001 Operación Correcta. No existen datos.", 274)},
            {"servicio": ("AEAT - CuentasAmpliadas (mod. 196):", 295),
             "resultado": ("0001 Operación Correcta. No existen datos.", 301)},
            {"servicio": ("AEAT - Consulta Fondos Inversion:", 322),
             "resultado": ("0001 Operación Correcta. No existen datos.", 328)},
            {"servicio": ("DFNavarra - Consulta Capacidad Economica:", 349),
             "resultado": ("0001 Operación Correcta. No existen datos.", 355)},
            {"servicio": ("SEPE - Consulta Prestaciones:", 376),
             "resultado": ("0001 Operación Correcta. No existen datos.", 382)},
            {"servicio": ("DGP - Consulta DNI:", 405),
             "resultado": ("Ok", 405)},
            {"servicio": ("INSS - Consulta Prestaciones Tarjeta Social Digital:", 423),
             "resultado": ("Ok", 434)},
            {"servicio": ("Entidades Financieras - Consultas por NIF:", 461),
             "resultado": ("Ok", 461)},
            {"servicio": ("DFGuipuzcoa - Consulta Capacidad Economica:", 488),
             "resultado": ("0001 Operacion Correcta. No existen datos.", 494)},
         ]},
     ]},

    # --- DGP - Consulta DNI (person identity) ---
    {"type": "section", "id": "dgp_consulta_dni", "title": "DGP - Consulta DNI",
     "y_hint": 526, "children": [
        {"type": "section", "id": "datos_personales", "title": "Datos Personales",
         "y_hint": 547, "children": [
            {"type": "kv_group", "id": "datos_personales_kv", "pairs": [
                {"label": "Nombre", "value": "GHEORGHE ADRIAN", "y_hint": 567},
                {"label": "Primer Apellido", "value": "OPREA", "y_hint": 587},
                {"label": "Segundo Apellido", "value": "", "y_hint": 607},
                {"label": "DNI", "value": "X6573514E", "y_hint": 627},
                {"label": "Nacionalidad", "value": "RUMANIA", "y_hint": 647},
                {"label": "Sexo", "value": "M", "y_hint": 667},
            ]},
        ]},
        {"type": "section", "id": "datos_nacimiento", "title": "Datos Nacimiento",
         "y_hint": 687, "children": [
            {"type": "kv_group", "id": "datos_nacimiento_kv", "pairs": [
                {"label": "Localidad", "value": "CLUJ", "y_hint": 707},
                {"label": "Provincia", "value": "ROU", "y_hint": 727},
                {"label": "Nombre del padre", "value": "GHEORGHE", "y_hint": 747},
            ]},
        ]},
     ]},

    # --- Footer legal prose + page footer ---
    # Verbatim concatenation of the four font_size=6.0 spans at y=771/778/785/792 (single-space join).
    {"type": "prose_block", "id": "aviso_legal", "label": "Aviso legal",
     "text": "La información obtenida a través del Punto Neutro Judicial únicamente puede "
             "utilizarse en el marco del procedimiento judicial correspondiente, sin que pueda "
             "comunicarse a terceros fuera de los "
             "casos permitidos por el ordenamiento jurídico. Dicha información, cuando se refiera "
             "a datos personales, está sometida al Reglamento General de Protección de Datos y la "
             "Ley Orgánica 3/2018, de 5 "
             "de diciembre, de Protección de Datos y Garantía de Derechos Digitales. El personal "
             "que acceda a esta información está sometido al cumplimiento del deber de secreto. El "
             "tratamiento de esta "
             "información deberá realizarse respetando las correspondientes medidas de seguridad "
             "que garanticen su integridad, disponibilidad y confidencialidad.",
     "y_hint": 771},
    {"type": "noise", "id": "footer_fecha", "kind": "logalty_metadata",
     "text": "17/04/26 17:13", "y_hint": 806},
    {"type": "noise", "id": "footer_pagina", "kind": "page_number",
     "text": "Página 1 de 4", "y_hint": 806},
]
