"""Golden structure spec for PATRIMONIAL .pdf page 2 (CGPJ Punto Neutro Judicial
"Consulta Integral Patrimonio" — continuation of person identity/address/document data).

Generated by golden-scaffolder. Walker-compatible types only.
Layout: a label/value form grid with two grey subsection-header rows
("Dirección", "Otros datos"). Several form slots are empty (no value in PDF).
"""

PDF = "/Users/carlos/Edelwyss/Projects/docomestria/Dataset/AZUREDOCUI/2_Example/PATRIMONIAL .pdf"
PAGE = 2

META = {
    "document_type": "Consulta Integral Patrimonio (PNJ)",
    "annotator": "scaffolder",
    "covers_cases": [
        "pnj_datos_identidad",
        "pnj_direccion_subsection",
        "pnj_otros_datos_subsection",
        "form_slot_empty_value",
        "page_footer_noise",
    ],
}


STRUCTURE = [
    {
        "type": "section",
        "id": "consulta_integral_patrimonio",
        "title": "Consulta Integral Patrimonio",
        "y_hint": 51,
        "children": [
            {
                "type": "table",
                "id": "datos_identidad",
                "title": "Datos de identidad",
                "y_hint": 103,
                "columns": [
                    {"id": "label", "label": "Campo", "type": "text"},
                    {"id": "value", "label": "Valor", "type": "text"},
                ],
                "rows": [
                    {"label": ("Nombre de la madre:", 103), "value": ("MARIA", 103)},
                    {"label": ("Fecha de nacimiento:", 123), "value": ("10/02/1978", 123)},
                ],
            },
            {
                "type": "section",
                "id": "direccion",
                "title": "Dirección",
                "y_hint": 143,
                "children": [
                    {
                        "type": "table",
                        "id": "direccion_datos",
                        "title": "Dirección",
                        "y_hint": 163,
                        "columns": [
                            {"id": "label", "label": "Campo", "type": "text"},
                            {"id": "value", "label": "Valor", "type": "text"},
                        ],
                        "rows": [
                            {"label": ("Localidad:", 163), "value": ("TERRASSA", 163)},
                            {"label": ("Provincia:", 183), "value": ("BARCELONA", 183)},
                            {"label": ("Código postal:", 203), "value": ("08227", 203)},
                            {"label": ("Domicilio:", 223), "value": ("AVENIDA MADRID, 238 PBJ", 223)},
                        ],
                    },
                ],
            },
            {
                "type": "section",
                "id": "otros_datos",
                "title": "Otros datos",
                "y_hint": 343,
                "children": [
                    {
                        "type": "table",
                        "id": "otros_datos_datos",
                        "title": "Otros datos",
                        "y_hint": 363,
                        "columns": [
                            {"id": "label", "label": "Campo", "type": "text"},
                            {"id": "value", "label": "Valor", "type": "text"},
                        ],
                        "rows": [
                            {"label": ("Fecha de expedición:", 363), "value": ("30/11/2011", 363)},
                            {"label": ("Equipo de expedición:", 383), "value": ("", 383)},
                            {"label": ("Fecha de caducidad:", 403), "value": ("01/01/9999", 403)},
                            {"label": ("Número de soporte:", 423), "value": ("C02572648", 423)},
                        ],
                    },
                ],
            },
        ],
    },
    {
        "type": "prose_block",
        "id": "aviso_legal",
        "label": "Aviso legal de uso de la información",
        "text": (
            "La información obtenida a través del Punto Neutro Judicial únicamente puede "
            "utilizarse en el marco del procedimiento judicial correspondiente, sin que pueda "
            "comunicarse a terceros fuera de los "
            "casos permitidos por el ordenamiento jurídico. Dicha información, cuando se refiera "
            "a datos personales, está sometida al Reglamento General de Protección de Datos y la "
            "Ley Orgánica 3/2018, de 5 "
            "de diciembre, de Protección de Datos y Garantía de Derechos Digitales. El personal "
            "que acceda a esta información está sometido al cumplimiento del deber de secreto. "
            "El tratamiento de esta "
            "información deberá realizarse respetando las correspondientes medidas de seguridad "
            "que garanticen su integridad, disponibilidad y confidencialidad."
        ),
        "y_hint": 771,
    },
    {
        "type": "noise",
        "id": "footer_timestamp",
        "text": "17/04/26 17:13",
        "kind": "logalty_metadata",
        "y_hint": 806,
    },
    {
        "type": "noise",
        "id": "footer_pagina",
        "text": "Página 2 de 4",
        "kind": "page_number",
        "y_hint": 806,
    },
    {
        "type": "noise",
        "id": "banner_cabecera",
        "text": "PLATAFORMA DE SERVICIOS DEL PUNTO NEUTRO JUDICIAL",
        "kind": "watermark",
        "y_hint": 36,
    },
]
